version: "2"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - depguard
    - errcheck
    - misspell

linters-settings:
  depguard:
    rules:
      no-sdkv2:
        deny:
          - pkg: github.com/hashicorp/terraform-plugin-sdk/v2
            desc: "Use terraform-plugin-framework or terraform-plugin-testing instead"


