version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - depguard
    - errcheck
    - misspell
  settings:
    depguard:
      rules:
        no-sdkv2:
          deny:
            - pkg: github.com/hashicorp/terraform-plugin-sdk/v2
              desc: "Use terraform-plugin-framework or terraform-plugin-testing instead"

formatters:
  enable:
    - gofmt
    - goimports


