// Code generated by tools/gen/client/main.go. DO NOT EDIT.

//go:build integration

package provider

import (
	resource "github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"testing"
)

func TestAccForemanResources_Basic(t *testing.T) {
	cases := []struct {
		resourceType string
		config       string
	}{{
		config:       providerConfig + "\nresource \"foreman_architecture\" \"test\" {\n  name = \"test-acc-architecture\"\n}\n",
		resourceType: "foreman_architecture",
	}, {
		config:       providerConfig + "\nresource \"foreman_autosign\" \"test\" {\n  name = \"test-acc-autosign\"\n}\n",
		resourceType: "foreman_autosign",
	}, {
		config:       providerConfig + "\nresource \"foreman_commonparameter\" \"test\" {\n  name = \"test-acc-commonparameter\"\n}\n",
		resourceType: "foreman_commonparameter",
	}, {
		config:       providerConfig + "\nresource \"foreman_computeprofile\" \"test\" {\n  name = \"test-acc-computeprofile\"\n}\n",
		resourceType: "foreman_computeprofile",
	}, {
		config:       providerConfig + "\nresource \"foreman_computeresource\" \"test\" {\n  name = \"test-acc-computeresource\"\n}\n",
		resourceType: "foreman_computeresource",
	}, {
		config:       providerConfig + "\nresource \"foreman_defaulttemplate\" \"test\" {\n  name = \"test-acc-defaulttemplate\"\n}\n",
		resourceType: "foreman_defaulttemplate",
	}, {
		config:       providerConfig + "\nresource \"foreman_domain\" \"test\" {\n  name = \"test-acc-domain\"\n}\n",
		resourceType: "foreman_domain",
	}, {
		config:       providerConfig + "\nresource \"foreman_httpproxy\" \"test\" {\n  name = \"test-acc-httpproxy\"\n}\n",
		resourceType: "foreman_httpproxy",
	}, {
		config:       providerConfig + "\nresource \"foreman_host\" \"test\" {\n  name = \"test-acc-host\"\n}\n",
		resourceType: "foreman_host",
	}, {
		config:       providerConfig + "\nresource \"foreman_hostgroup\" \"test\" {\n  name = \"test-acc-hostgroup\"\n}\n",
		resourceType: "foreman_hostgroup",
	}, {
		config:       providerConfig + "\nresource \"foreman_image\" \"test\" {\n  name = \"test-acc-image\"\n}\n",
		resourceType: "foreman_image",
	}, {
		config:       providerConfig + "\nresource \"foreman_media\" \"test\" {\n  name = \"test-acc-media\"\n}\n",
		resourceType: "foreman_media",
	}, {
		config:       providerConfig + "\nresource \"foreman_model\" \"test\" {\n  name = \"test-acc-model\"\n}\n",
		resourceType: "foreman_model",
	}, {
		config:       providerConfig + "\nresource \"foreman_operatingsystem\" \"test\" {\n  name = \"test-acc-operatingsystem\"\n}\n",
		resourceType: "foreman_operatingsystem",
	}, {
		config:       providerConfig + "\nresource \"foreman_parameter\" \"test\" {\n  name = \"test-acc-parameter\"\n}\n",
		resourceType: "foreman_parameter",
	}, {
		config:       providerConfig + "\nresource \"foreman_partitiontable\" \"test\" {\n  name = \"test-acc-partitiontable\"\n}\n",
		resourceType: "foreman_partitiontable",
	}, {
		config:       providerConfig + "\nresource \"foreman_provisioningtemplate\" \"test\" {\n  name = \"test-acc-provisioningtemplate\"\n}\n",
		resourceType: "foreman_provisioningtemplate",
	}, {
		config:       providerConfig + "\nresource \"foreman_realm\" \"test\" {\n  name = \"test-acc-realm\"\n}\n",
		resourceType: "foreman_realm",
	}, {
		config:       providerConfig + "\nresource \"foreman_setting\" \"test\" {\n  name = \"test-acc-setting\"\n}\n",
		resourceType: "foreman_setting",
	}, {
		config:       providerConfig + "\nresource \"foreman_smartproxy\" \"test\" {\n  name = \"test-acc-smartproxy\"\n}\n",
		resourceType: "foreman_smartproxy",
	}, {
		config:       providerConfig + "\nresource \"foreman_subnet\" \"test\" {\n  name = \"test-acc-subnet\"\n}\n",
		resourceType: "foreman_subnet",
	}, {
		config:       providerConfig + "\nresource \"foreman_templateinput\" \"test\" {\n  name = \"test-acc-templateinput\"\n}\n",
		resourceType: "foreman_templateinput",
	}, {
		config:       providerConfig + "\nresource \"foreman_user\" \"test\" {\n  name = \"test-acc-user\"\n}\n",
		resourceType: "foreman_user",
	}, {
		config:       providerConfig + "\nresource \"foreman_usergroup\" \"test\" {\n  name = \"test-acc-usergroup\"\n}\n",
		resourceType: "foreman_usergroup",
	}, {
		config:       providerConfig + "\nresource \"foreman_environment\" \"test\" {\n  name = \"test-acc-environment\"\n}\n",
		resourceType: "foreman_environment",
	}, {
		config:       providerConfig + "\nresource \"foreman_jobtemplate\" \"test\" {\n  name = \"test-acc-jobtemplate\"\n}\n",
		resourceType: "foreman_jobtemplate",
	}, {
		config:       providerConfig + "\nresource \"foreman_puppetclass\" \"test\" {\n  name = \"test-acc-puppetclass\"\n}\n",
		resourceType: "foreman_puppetclass",
	}, {
		config:       providerConfig + "\nresource \"foreman_smartclassparameter\" \"test\" {\n  name = \"test-acc-smartclassparameter\"\n}\n",
		resourceType: "foreman_smartclassparameter",
	}, {
		config:       providerConfig + "\nresource \"foreman_templatekind\" \"test\" {\n  name = \"test-acc-templatekind\"\n}\n",
		resourceType: "foreman_templatekind",
	}, {
		config:       providerConfig + "\nresource \"foreman_discovery_rule\" \"test\" {\n  name = \"test-acc-discovery_rule\"\n}\n",
		resourceType: "foreman_discovery_rule",
	}, {
		config:       providerConfig + "\nresource \"foreman_webhook\" \"test\" {\n  name = \"test-acc-webhook\"\n}\n",
		resourceType: "foreman_webhook",
	}, {
		config:       providerConfig + "\nresource \"foreman_webhooktemplate\" \"test\" {\n  name = \"test-acc-webhooktemplate\"\n}\n",
		resourceType: "foreman_webhooktemplate",
	}, {
		config:       providerConfig + "\nresource \"foreman_override_value\" \"test\" {\n  name = \"test-acc-override_value\"\n}\n",
		resourceType: "foreman_override_value",
	}}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.resourceType, func(t *testing.T) {
			t.Parallel()
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories(),
				Steps: []resource.TestStep{{
					Check:  resource.ComposeAggregateTestCheckFunc(resource.TestCheckResourceAttrSet(tc.resourceType+".test", "id"), resource.TestCheckResourceAttr(tc.resourceType+".test", "name", "test-acc-"+tc.resourceType[8:])),
					Config: tc.config,
				}, {
					ImportState:       true,
					ImportStateVerify: true,
					ResourceName:      tc.resourceType + ".test",
				}},
			})
		})
	}
}
