// Code generated by tools/gen/client/main.go. DO NOT EDIT.
//go:build integration

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccForemanResources_Basic(t *testing.T) {
	cases := []struct {
		resourceType string
		config       string
	}{
		{
			resourceType: "foreman_architecture",
			config: providerConfig + `
resource "foreman_architecture" "test" {
  name = "test-acc-architecture"
}
`,
		},
		{
			resourceType: "foreman_autosign",
			config: providerConfig + `
resource "foreman_autosign" "test" {
  name = "test-acc-autosign"
}
`,
		},
		{
			resourceType: "foreman_commonparameter",
			config: providerConfig + `
resource "foreman_commonparameter" "test" {
  name = "test-acc-commonparameter"
}
`,
		},
		{
			resourceType: "foreman_computeprofile",
			config: providerConfig + `
resource "foreman_computeprofile" "test" {
  name = "test-acc-computeprofile"
}
`,
		},
		{
			resourceType: "foreman_computeresource",
			config: providerConfig + `
resource "foreman_computeresource" "test" {
  name = "test-acc-computeresource"
}
`,
		},
		{
			resourceType: "foreman_defaulttemplate",
			config: providerConfig + `
resource "foreman_defaulttemplate" "test" {
  name = "test-acc-defaulttemplate"
}
`,
		},
		{
			resourceType: "foreman_domain",
			config: providerConfig + `
resource "foreman_domain" "test" {
  name = "test-acc-domain"
}
`,
		},
		{
			resourceType: "foreman_httpproxy",
			config: providerConfig + `
resource "foreman_httpproxy" "test" {
  name = "test-acc-httpproxy"
}
`,
		},
		{
			resourceType: "foreman_host",
			config: providerConfig + `
resource "foreman_host" "test" {
  name = "test-acc-host"
}
`,
		},
		{
			resourceType: "foreman_hostgroup",
			config: providerConfig + `
resource "foreman_hostgroup" "test" {
  name = "test-acc-hostgroup"
}
`,
		},
		{
			resourceType: "foreman_image",
			config: providerConfig + `
resource "foreman_image" "test" {
  name = "test-acc-image"
}
`,
		},
		{
			resourceType: "foreman_medium",
			config: providerConfig + `
resource "foreman_medium" "test" {
  name = "test-acc-medium"
}
`,
		},
		{
			resourceType: "foreman_model",
			config: providerConfig + `
resource "foreman_model" "test" {
  name = "test-acc-model"
}
`,
		},
		{
			resourceType: "foreman_operatingsystem",
			config: providerConfig + `
resource "foreman_operatingsystem" "test" {
  name = "test-acc-operatingsystem"
}
`,
		},
		{
			resourceType: "foreman_parameter",
			config: providerConfig + `
resource "foreman_parameter" "test" {
  name = "test-acc-parameter"
}
`,
		},
		{
			resourceType: "foreman_partitiontable",
			config: providerConfig + `
resource "foreman_partitiontable" "test" {
  name = "test-acc-partitiontable"
}
`,
		},
		{
			resourceType: "foreman_provisioningtemplate",
			config: providerConfig + `
resource "foreman_provisioningtemplate" "test" {
  name = "test-acc-provisioningtemplate"
}
`,
		},
		{
			resourceType: "foreman_realm",
			config: providerConfig + `
resource "foreman_realm" "test" {
  name = "test-acc-realm"
}
`,
		},
		{
			resourceType: "foreman_setting",
			config: providerConfig + `
resource "foreman_setting" "test" {
  name = "test-acc-setting"
}
`,
		},
		{
			resourceType: "foreman_smartproxy",
			config: providerConfig + `
resource "foreman_smartproxy" "test" {
  name = "test-acc-smartproxy"
}
`,
		},
		{
			resourceType: "foreman_subnet",
			config: providerConfig + `
resource "foreman_subnet" "test" {
  name = "test-acc-subnet"
}
`,
		},
		{
			resourceType: "foreman_templateinput",
			config: providerConfig + `
resource "foreman_templateinput" "test" {
  name = "test-acc-templateinput"
}
`,
		},
		{
			resourceType: "foreman_user",
			config: providerConfig + `
resource "foreman_user" "test" {
  name = "test-acc-user"
}
`,
		},
		{
			resourceType: "foreman_usergroup",
			config: providerConfig + `
resource "foreman_usergroup" "test" {
  name = "test-acc-usergroup"
}
`,
		},
		{
			resourceType: "foreman_environment",
			config: providerConfig + `
resource "foreman_environment" "test" {
  name = "test-acc-environment"
}
`,
		},
		{
			resourceType: "foreman_job_template",
			config: providerConfig + `
resource "foreman_job_template" "test" {
  name = "test-acc-job_template"
}
`,
		},
		{
			resourceType: "foreman_puppetclass",
			config: providerConfig + `
resource "foreman_puppetclass" "test" {
  name = "test-acc-puppetclass"
}
`,
		},
		{
			resourceType: "foreman_smartclassparameter",
			config: providerConfig + `
resource "foreman_smartclassparameter" "test" {
  name = "test-acc-smartclassparameter"
}
`,
		},
		{
			resourceType: "foreman_templatekind",
			config: providerConfig + `
resource "foreman_templatekind" "test" {
  name = "test-acc-templatekind"
}
`,
		},
		{
			resourceType: "foreman_discovery_rule",
			config: providerConfig + `
resource "foreman_discovery_rule" "test" {
  name = "test-acc-discovery_rule"
}
`,
		},
		{
			resourceType: "foreman_webhook",
			config: providerConfig + `
resource "foreman_webhook" "test" {
  name = "test-acc-webhook"
}
`,
		},
		{
			resourceType: "foreman_webhook_template",
			config: providerConfig + `
resource "foreman_webhook_template" "test" {
  name = "test-acc-webhook_template"
}
`,
		},
		{
			resourceType: "foreman_override_value",
			config: providerConfig + `
resource "foreman_override_value" "test" {
  name = "test-acc-override_value"
}
`,
		},
	}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.resourceType, func(t *testing.T) {
			t.Parallel()
			resource.Test(t, resource.TestCase{
				ProtoV6ProviderFactories: testAccProtoV6ProviderFactories(),
				Steps: []resource.TestStep{
					{
						Config: tc.config,
						Check: resource.ComposeAggregateTestCheckFunc(
							resource.TestCheckResourceAttrSet(tc.resourceType+".test", "id"),
							resource.TestCheckResourceAttr(tc.resourceType+".test", "name", "test-acc-"+tc.resourceType[len("foreman_"):]),
						),
					},
					{
						ResourceName:      tc.resourceType + ".test",
						ImportState:       true,
						ImportStateVerify: true,
					},
				},
			})
		})
	}
}
