// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ datasource.DataSource = &partitiontableDataSource{}
)

func NewForemanPartitionTableDataSource() datasource.DataSource {
	return &partitiontableDataSource{}
}

type partitiontableDataSource struct {
	client *generated.ForemanClient
}

type partitiontableDataSourceModel struct {
	ID           types.String `tfsdk:"id"`
	Name         types.String `tfsdk:"name"`
	Layout       types.String `tfsdk:"layout"`
	AuditComment types.String `tfsdk:"audit_comment"`
	Description  types.String `tfsdk:"description"`
	Locked       types.Bool   `tfsdk:"locked"`
	OsFamily     types.String `tfsdk:"os_family"`
	Snippet      types.Bool   `tfsdk:"snippet"`
}

func (d *partitiontableDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_partitiontable"
}

func (d *partitiontableDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "The name of the partitiontable to look up.",
			},
			"layout": schema.StringAttribute{
				Computed: true,
			},
			"audit_comment": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"locked": schema.BoolAttribute{
				Computed:    true,
				Description: "Whether or not the template is locked for editing",
			},
			"os_family": schema.StringAttribute{
				Computed: true,
			},
			"snippet": schema.BoolAttribute{
				Computed: true,
			},
		},
	}
}

func (d *partitiontableDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	d.client = client
}

func (d *partitiontableDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data partitiontableDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	name := data.Name.ValueString()
	result, err := d.client.QueryForemanPartitionTable(ctx, name)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read partitiontable, got error: %s", err))
		return
	}
	if result == nil {
		resp.Diagnostics.AddError("Not Found", fmt.Sprintf("ForemanPartitionTable %q not found", name))
		return
	}

	data.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	data.Layout = types.StringValue(result.Layout)
	data.AuditComment = types.StringValue(result.AuditComment)
	data.Description = types.StringValue(result.Description)
	data.Locked = types.BoolValue(result.Locked)
	data.OsFamily = types.StringValue(result.OsFamily)
	data.Snippet = types.BoolValue(result.Snippet)

	tflog.Trace(ctx, "read partitiontable data source", map[string]interface{}{"id": data.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
