// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	schema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	generated "github.com/terraform-coop/terraform-provider-foreman/generated"
	"strconv"
)

var _ datasource.DataSource = &provisioningtemplateDataSource{}

func NewForemanProvisioningTemplateDataSource() datasource.DataSource {
	return &provisioningtemplateDataSource{}
}

type provisioningtemplateDataSource struct {
	client *generated.ForemanClient
}

type provisioningtemplateDataSourceModel struct {
	ID             types.String `tfsdk:"id"`
	Name           types.String `tfsdk:"name"`
	Template       types.String `tfsdk:"template"`
	AuditComment   types.String `tfsdk:"audit_comment"`
	Description    types.String `tfsdk:"description"`
	Locked         types.Bool   `tfsdk:"locked"`
	Snippet        types.Bool   `tfsdk:"snippet"`
	TemplateKindID types.Int64  `tfsdk:"template_kind_id"`
}

func (d *provisioningtemplateDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_provisioningtemplate"
}

func (d *provisioningtemplateDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{Attributes: map[string]schema.Attribute{
		"id": schema.StringAttribute{Computed: true},
		"name": schema.StringAttribute{
			Description: "The name of the provisioningtemplate to look up.",
			Required:    true,
		},
	}}
}

func (d *provisioningtemplateDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	d.client = client
}

func (d *provisioningtemplateDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data provisioningtemplateDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	name := data.Name.ValueString()
	result, err := d.client.QueryForemanProvisioningTemplate(ctx, name)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read provisioningtemplate, got error: %s", err))
		return
	}
	if result == nil {
		resp.Diagnostics.AddError("Not Found", fmt.Sprintf("ForemanProvisioningTemplate %q not found", name))
		return
	}

	data.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	data.Template = types.StringValue(result.Template)
	data.AuditComment = types.StringValue(result.AuditComment)
	data.Description = types.StringValue(result.Description)
	data.Locked = types.BoolValue(result.Locked)
	data.Snippet = types.BoolValue(result.Snippet)
	data.TemplateKindID = types.Int64Value(int64(result.TemplateKindID))

	tflog.Trace(ctx, "read provisioningtemplate data source", map[string]interface{}{"id": data.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
