// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ datasource.DataSource = &userDataSource{}
)

func NewForemanUserDataSource() datasource.DataSource {
	return &userDataSource{}
}

type userDataSource struct {
	client *generated.ForemanClient
}

type userDataSourceModel struct {
	ID                    types.String `tfsdk:"id"`
	Name                  types.String `tfsdk:"name"`
	AuthSourceID          types.Int64  `tfsdk:"auth_source_id"`
	Login                 types.String `tfsdk:"login"`
	Mail                  types.String `tfsdk:"mail"`
	Admin                 types.Bool   `tfsdk:"admin"`
	DefaultLocationID     types.Int64  `tfsdk:"default_location_id"`
	DefaultOrganizationID types.Int64  `tfsdk:"default_organization_id"`
	Description           types.String `tfsdk:"description"`
	Disabled              types.Bool   `tfsdk:"disabled"`
	Firstname             types.String `tfsdk:"firstname"`
	Lastname              types.String `tfsdk:"lastname"`
	Locale                types.String `tfsdk:"locale"`
	MailEnabled           types.Bool   `tfsdk:"mail_enabled"`
	Password              types.String `tfsdk:"password"`
	Timezone              types.String `tfsdk:"timezone"`
	UiCompactMode         types.Bool   `tfsdk:"ui_compact_mode"`
}

func (d *userDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_user"
}

func (d *userDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "The name of the user to look up.",
			},
			"auth_source_id": schema.Int64Attribute{
				Computed: true,
			},
			"login": schema.StringAttribute{
				Computed: true,
			},
			"mail": schema.StringAttribute{
				Computed: true,
			},
			"admin": schema.BoolAttribute{
				Computed:    true,
				Description: "is an admin account",
			},
			"default_location_id": schema.Int64Attribute{
				Computed: true,
			},
			"default_organization_id": schema.Int64Attribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"disabled": schema.BoolAttribute{
				Computed: true,
			},
			"firstname": schema.StringAttribute{
				Computed: true,
			},
			"lastname": schema.StringAttribute{
				Computed: true,
			},
			"locale": schema.StringAttribute{
				Computed:    true,
				Description: "User&#39;s preferred locale",
			},
			"mail_enabled": schema.BoolAttribute{
				Computed:    true,
				Description: "Enable user&#39;s email",
			},
			"password": schema.StringAttribute{
				Computed:    true,
				Description: "Required unless user is in an external authentication source",
			},
			"timezone": schema.StringAttribute{
				Computed:    true,
				Description: "User&#39;s timezone",
			},
			"ui_compact_mode": schema.BoolAttribute{
				Computed:    true,
				Description: "Use compact UI",
			},
		},
	}
}

func (d *userDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	d.client = client
}

func (d *userDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data userDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	name := data.Name.ValueString()
	result, err := d.client.QueryForemanUser(ctx, name)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read user, got error: %s", err))
		return
	}
	if result == nil {
		resp.Diagnostics.AddError("Not Found", fmt.Sprintf("ForemanUser %q not found", name))
		return
	}

	data.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	data.AuthSourceID = types.Int64Value(int64(result.AuthSourceID))
	data.Login = types.StringValue(result.Login)
	data.Mail = types.StringValue(result.Mail)
	data.Admin = types.BoolValue(result.Admin)
	data.DefaultLocationID = types.Int64Value(int64(result.DefaultLocationID))
	data.DefaultOrganizationID = types.Int64Value(int64(result.DefaultOrganizationID))
	data.Description = types.StringValue(result.Description)
	data.Disabled = types.BoolValue(result.Disabled)
	data.Firstname = types.StringValue(result.Firstname)
	data.Lastname = types.StringValue(result.Lastname)
	data.Locale = types.StringValue(result.Locale)
	data.MailEnabled = types.BoolValue(result.MailEnabled)
	data.Password = types.StringValue(result.Password)
	data.Timezone = types.StringValue(result.Timezone)
	data.UiCompactMode = types.BoolValue(result.UiCompactMode)

	tflog.Trace(ctx, "read user data source", map[string]interface{}{"id": data.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
