// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsdchema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ datasource.DataSource = &hostDataSource{}
)

func NewForemanHostDataSource() datasource.DataSource {
	return &hostDataSource{}
}

type hostDataSource struct {
	client *generated.ForemanClient
}

type hostDataSourceModel struct {
	ID                      types.String `tfsdk:"id"`
	Name                    types.String `tfsdk:"name"`
	ArchitectureID          types.Int64  `tfsdk:"architecture_id"`
	BmcAvailable            types.Bool   `tfsdk:"bmc_available"`
	Build                   types.Bool   `tfsdk:"build"`
	BuildStatus             types.Int64  `tfsdk:"build_status"`
	BuildStatusLabel        types.String `tfsdk:"build_status_label"`
	Certname                types.String `tfsdk:"certname"`
	Comment                 types.String `tfsdk:"comment"`
	ComputeProfileID        types.String `tfsdk:"compute_profile_id"`
	ComputeResourceID       types.Int64  `tfsdk:"compute_resource_id"`
	ComputeResourceProvider types.String `tfsdk:"compute_resource_provider"`
	Creator                 types.String `tfsdk:"creator"`
	CreatorID               types.Int64  `tfsdk:"creator_id"`
	Disk                    types.String `tfsdk:"disk"`
	DisplayName             types.String `tfsdk:"display_name"`
	DomainID                types.Int64  `tfsdk:"domain_id"`
	Enabled                 types.Bool   `tfsdk:"enabled"`
	GlobalStatus            types.Int64  `tfsdk:"global_status"`
	GlobalStatusLabel       types.String `tfsdk:"global_status_label"`
	HostgroupID             types.Int64  `tfsdk:"hostgroup_id"`
	ImageID                 types.String `tfsdk:"image_id"`
	InitiatedAt             types.String `tfsdk:"initiated_at"`
	InstalledAt             types.String `tfsdk:"installed_at"`
	IP                      types.String `tfsdk:"ip"`
	IP6                     types.String `tfsdk:"ip6"`
	LastCompile             types.String `tfsdk:"last_compile"`
	LastReport              types.String `tfsdk:"last_report"`
	MAC                     types.String `tfsdk:"mac"`
	Managed                 types.Bool   `tfsdk:"managed"`
	MediumID                types.Int64  `tfsdk:"medium_id"`
	ModelID                 types.String `tfsdk:"model_id"`
	OperatingsystemIcon     types.String `tfsdk:"operatingsystem_icon"`
	OperatingsystemID       types.Int64  `tfsdk:"operatingsystem_id"`
	OwnerID                 types.Int64  `tfsdk:"owner_id"`
	OwnerType               types.String `tfsdk:"owner_type"`
	Permissions             types.Map    `tfsdk:"permissions"`
	ProvisionMethod         types.String `tfsdk:"provision_method"`
	PtableID                types.Int64  `tfsdk:"ptable_id"`
	PuppetCaProxyID         types.String `tfsdk:"puppet_ca_proxy_id"`
	PuppetProxyID           types.String `tfsdk:"puppet_proxy_id"`
	PXELoader               types.String `tfsdk:"pxe_loader"`
	RealmID                 types.String `tfsdk:"realm_id"`
	RebuildRequiresPoweroff types.Bool   `tfsdk:"rebuild_requires_poweroff"`
	SpIP                    types.String `tfsdk:"sp_ip"`
	SpMAC                   types.String `tfsdk:"sp_mac"`
	SpName                  types.String `tfsdk:"sp_name"`
	SpSubnetID              types.String `tfsdk:"sp_subnet_id"`
	Subnet6ID               types.String `tfsdk:"subnet6_id"`
	SubnetID                types.String `tfsdk:"subnet_id"`
	UseImage                types.String `tfsdk:"use_image"`
}

func (d *hostDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_host"
}

func (d *hostDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsdchema.Schema{
		Attributes: map[string]dsdchema.Attribute{
			"id": dsdchema.StringAttribute{
				Computed: true,
			},
			"name": dsdchema.StringAttribute{
				Required:    true,
				Description: "The name of the host to look up.",
			},
			"architecture_id": dsdchema.Int64Attribute{
				Computed: true,
			},
			"bmc_available": dsdchema.BoolAttribute{
				Computed: true,
			},
			"build": dsdchema.BoolAttribute{
				Computed: true,
			},
			"build_status": dsdchema.Int64Attribute{
				Computed: true,
			},
			"build_status_label": dsdchema.StringAttribute{
				Computed: true,
			},
			"certname": dsdchema.StringAttribute{
				Computed: true,
			},
			"comment": dsdchema.StringAttribute{
				Computed: true,
			},
			"compute_profile_id": dsdchema.StringAttribute{
				Computed: true,
			},
			"compute_resource_id": dsdchema.Int64Attribute{
				Computed: true,
			},
			"compute_resource_provider": dsdchema.StringAttribute{
				Computed: true,
			},
			"creator": dsdchema.StringAttribute{
				Computed: true,
			},
			"creator_id": dsdchema.Int64Attribute{
				Computed: true,
			},
			"disk": dsdchema.StringAttribute{
				Computed: true,
			},
			"display_name": dsdchema.StringAttribute{
				Computed: true,
			},
			"domain_id": dsdchema.Int64Attribute{
				Computed: true,
			},
			"enabled": dsdchema.BoolAttribute{
				Computed: true,
			},
			"global_status": dsdchema.Int64Attribute{
				Computed: true,
			},
			"global_status_label": dsdchema.StringAttribute{
				Computed: true,
			},
			"hostgroup_id": dsdchema.Int64Attribute{
				Computed: true,
			},
			"image_id": dsdchema.StringAttribute{
				Computed: true,
			},
			"initiated_at": dsdchema.StringAttribute{
				Computed: true,
			},
			"installed_at": dsdchema.StringAttribute{
				Computed: true,
			},
			"ip": dsdchema.StringAttribute{
				Computed: true,
			},
			"ip6": dsdchema.StringAttribute{
				Computed: true,
			},
			"last_compile": dsdchema.StringAttribute{
				Computed: true,
			},
			"last_report": dsdchema.StringAttribute{
				Computed: true,
			},
			"mac": dsdchema.StringAttribute{
				Computed: true,
			},
			"managed": dsdchema.BoolAttribute{
				Computed: true,
			},
			"medium_id": dsdchema.Int64Attribute{
				Computed: true,
			},
			"model_id": dsdchema.StringAttribute{
				Computed: true,
			},
			"operatingsystem_icon": dsdchema.StringAttribute{
				Computed: true,
			},
			"operatingsystem_id": dsdchema.Int64Attribute{
				Computed: true,
			},
			"owner_id": dsdchema.Int64Attribute{
				Computed: true,
			},
			"owner_type": dsdchema.StringAttribute{
				Computed: true,
			},
			"permissions": dsdchema.MapAttribute{
				Computed: true,
			},
			"provision_method": dsdchema.StringAttribute{
				Computed: true,
			},
			"ptable_id": dsdchema.Int64Attribute{
				Computed: true,
			},
			"puppet_ca_proxy_id": dsdchema.StringAttribute{
				Computed: true,
			},
			"puppet_proxy_id": dsdchema.StringAttribute{
				Computed: true,
			},
			"pxe_loader": dsdchema.StringAttribute{
				Computed: true,
			},
			"realm_id": dsdchema.StringAttribute{
				Computed: true,
			},
			"rebuild_requires_poweroff": dsdchema.BoolAttribute{
				Computed: true,
			},
			"sp_ip": dsdchema.StringAttribute{
				Computed: true,
			},
			"sp_mac": dsdchema.StringAttribute{
				Computed: true,
			},
			"sp_name": dsdchema.StringAttribute{
				Computed: true,
			},
			"sp_subnet_id": dsdchema.StringAttribute{
				Computed: true,
			},
			"subnet6_id": dsdchema.StringAttribute{
				Computed: true,
			},
			"subnet_id": dsdchema.StringAttribute{
				Computed: true,
			},
			"use_image": dsdchema.StringAttribute{
				Computed: true,
			},
		},
	}
}

func (d *hostDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	d.client = client
}

func (d *hostDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data hostDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	name := data.Name.ValueString()
	result, err := d.client.QueryForemanHost(ctx, name)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read host, got error: %s", err))
		return
	}
	if result == nil {
		resp.Diagnostics.AddError("Not Found", fmt.Sprintf("ForemanHost %q not found", name))
		return
	}

	data.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	data.ArchitectureID = types.Int64Value(int64(result.ArchitectureID))
	data.BmcAvailable = types.BoolValue(result.BmcAvailable)
	data.Build = types.BoolValue(result.Build)
	data.BuildStatus = types.Int64Value(int64(result.BuildStatus))
	data.BuildStatusLabel = types.StringValue(result.BuildStatusLabel)
	data.Certname = types.StringValue(result.Certname)
	data.Comment = types.StringValue(result.Comment)
	data.ComputeProfileID = types.StringValue(result.ComputeProfileID)
	data.ComputeResourceID = types.Int64Value(int64(result.ComputeResourceID))
	data.ComputeResourceProvider = types.StringValue(result.ComputeResourceProvider)
	data.Creator = types.StringValue(result.Creator)
	data.CreatorID = types.Int64Value(int64(result.CreatorID))
	data.Disk = types.StringValue(result.Disk)
	data.DisplayName = types.StringValue(result.DisplayName)
	data.DomainID = types.Int64Value(int64(result.DomainID))
	data.Enabled = types.BoolValue(result.Enabled)
	data.GlobalStatus = types.Int64Value(int64(result.GlobalStatus))
	data.GlobalStatusLabel = types.StringValue(result.GlobalStatusLabel)
	data.HostgroupID = types.Int64Value(int64(result.HostgroupID))
	data.ImageID = types.StringValue(result.ImageID)
	data.InitiatedAt = types.StringValue(result.InitiatedAt)
	data.InstalledAt = types.StringValue(result.InstalledAt)
	data.IP = types.StringValue(result.IP)
	data.IP6 = types.StringValue(result.IP6)
	data.LastCompile = types.StringValue(result.LastCompile)
	data.LastReport = types.StringValue(result.LastReport)
	data.MAC = types.StringValue(result.MAC)
	data.Managed = types.BoolValue(result.Managed)
	data.MediumID = types.Int64Value(int64(result.MediumID))
	data.ModelID = types.StringValue(result.ModelID)
	data.OperatingsystemIcon = types.StringValue(result.OperatingsystemIcon)
	data.OperatingsystemID = types.Int64Value(int64(result.OperatingsystemID))
	data.OwnerID = types.Int64Value(int64(result.OwnerID))
	data.OwnerType = types.StringValue(result.OwnerType)
	data.ProvisionMethod = types.StringValue(result.ProvisionMethod)
	data.PtableID = types.Int64Value(int64(result.PtableID))
	data.PuppetCaProxyID = types.StringValue(result.PuppetCaProxyID)
	data.PuppetProxyID = types.StringValue(result.PuppetProxyID)
	data.PXELoader = types.StringValue(result.PXELoader)
	data.RealmID = types.StringValue(result.RealmID)
	data.RebuildRequiresPoweroff = types.BoolValue(result.RebuildRequiresPoweroff)
	data.SpIP = types.StringValue(result.SpIP)
	data.SpMAC = types.StringValue(result.SpMAC)
	data.SpName = types.StringValue(result.SpName)
	data.SpSubnetID = types.StringValue(result.SpSubnetID)
	data.Subnet6ID = types.StringValue(result.Subnet6ID)
	data.SubnetID = types.StringValue(result.SubnetID)
	data.UseImage = types.StringValue(result.UseImage)

	tflog.Trace(ctx, "read host data source", map[string]interface{}{"id": data.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
