// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ datasource.DataSource = &subnetDataSource{}
)

func NewForemanSubnetDataSource() datasource.DataSource {
	return &subnetDataSource{}
}

type subnetDataSource struct {
	client *generated.ForemanClient
}

type subnetDataSourceModel struct {
	ID                types.String `tfsdk:"id"`
	Name              types.String `tfsdk:"name"`
	Network           types.String `tfsdk:"network"`
	BmcID             types.Int64  `tfsdk:"bmc_id"`
	BootMode          types.String `tfsdk:"boot_mode"`
	Cidr              types.String `tfsdk:"cidr"`
	Description       types.String `tfsdk:"description"`
	DhcpID            types.Int64  `tfsdk:"dhcp_id"`
	DNSID             types.Int64  `tfsdk:"dns_id"`
	DNSPrimary        types.String `tfsdk:"dns_primary"`
	DNSSecondary      types.String `tfsdk:"dns_secondary"`
	ExternalipamGroup types.String `tfsdk:"externalipam_group"`
	ExternalipamID    types.Int64  `tfsdk:"externalipam_id"`
	From              types.String `tfsdk:"from"`
	Gateway           types.String `tfsdk:"gateway"`
	HTTPbootID        types.Int64  `tfsdk:"httpboot_id"`
	IPam              types.String `tfsdk:"ipam"`
	Mask              types.String `tfsdk:"mask"`
	Mtu               types.Int64  `tfsdk:"mtu"`
	NetworkType       types.String `tfsdk:"network_type"`
	TemplateID        types.Int64  `tfsdk:"template_id"`
	TftpID            types.Int64  `tfsdk:"tftp_id"`
	To                types.String `tfsdk:"to"`
	Vlanid            types.String `tfsdk:"vlanid"`
}

func (d *subnetDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_subnet"
}

func (d *subnetDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "The name of the subnet to look up.",
			},
			"network": schema.StringAttribute{
				Computed:    true,
				Description: "Subnet network",
			},
			"bmc_id": schema.Int64Attribute{
				Computed:    true,
				Description: "BMC Proxy ID to use within this subnet",
			},
			"boot_mode": schema.StringAttribute{
				Computed:    true,
				Description: "Default boot mode for interfaces assigned to this subnet.",
			},
			"cidr": schema.StringAttribute{
				Computed:    true,
				Description: "Network prefix in CIDR notation",
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Description: "Subnet description",
			},
			"dhcp_id": schema.Int64Attribute{
				Computed:    true,
				Description: "DHCP Proxy ID to use within this subnet",
			},
			"dns_id": schema.Int64Attribute{
				Computed:    true,
				Description: "DNS Proxy ID to use within this subnet",
			},
			"dns_primary": schema.StringAttribute{
				Computed:    true,
				Description: "Primary DNS for this subnet",
			},
			"dns_secondary": schema.StringAttribute{
				Computed:    true,
				Description: "Secondary DNS for this subnet",
			},
			"externalipam_group": schema.StringAttribute{
				Computed:    true,
				Description: "External IPAM group - only relevant when IPAM is set to external",
			},
			"externalipam_id": schema.Int64Attribute{
				Computed:    true,
				Description: "External IPAM Proxy ID to use within this subnet",
			},
			"from": schema.StringAttribute{
				Computed:    true,
				Description: "Starting IP Address for IP auto suggestion",
			},
			"gateway": schema.StringAttribute{
				Computed:    true,
				Description: "Subnet gateway",
			},
			"httpboot_id": schema.Int64Attribute{
				Computed:    true,
				Description: "HTTPBoot Proxy ID to use within this subnet",
			},
			"ipam": schema.StringAttribute{
				Computed:    true,
				Description: "IP Address auto suggestion mode for this subnet.",
			},
			"mask": schema.StringAttribute{
				Computed:    true,
				Description: "Netmask for this subnet",
			},
			"mtu": schema.Int64Attribute{
				Computed:    true,
				Description: "MTU for this subnet",
			},
			"network_type": schema.StringAttribute{
				Computed:    true,
				Description: "Type or protocol, IPv4 or IPv6, defaults to IPv4",
			},
			"template_id": schema.Int64Attribute{
				Computed:    true,
				Description: "Template HTTP(S) Proxy ID to use within this subnet",
			},
			"tftp_id": schema.Int64Attribute{
				Computed:    true,
				Description: "TFTP Proxy ID to use within this subnet",
			},
			"to": schema.StringAttribute{
				Computed:    true,
				Description: "Ending IP Address for IP auto suggestion",
			},
			"vlanid": schema.StringAttribute{
				Computed:    true,
				Description: "VLAN ID for this subnet",
			},
		},
	}
}

func (d *subnetDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	d.client = client
}

func (d *subnetDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data subnetDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	name := data.Name.ValueString()
	result, err := d.client.QueryForemanSubnet(ctx, name)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read subnet, got error: %s", err))
		return
	}
	if result == nil {
		resp.Diagnostics.AddError("Not Found", fmt.Sprintf("ForemanSubnet %q not found", name))
		return
	}

	data.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	data.Network = types.StringValue(result.Network)
	data.BmcID = types.Int64Value(int64(result.BmcID))
	data.BootMode = types.StringValue(result.BootMode)
	data.Cidr = types.StringValue(result.Cidr)
	data.Description = types.StringValue(result.Description)
	data.DhcpID = types.Int64Value(int64(result.DhcpID))
	data.DNSID = types.Int64Value(int64(result.DNSID))
	data.DNSPrimary = types.StringValue(result.DNSPrimary)
	data.DNSSecondary = types.StringValue(result.DNSSecondary)
	data.ExternalipamGroup = types.StringValue(result.ExternalipamGroup)
	data.ExternalipamID = types.Int64Value(int64(result.ExternalipamID))
	data.From = types.StringValue(result.From)
	data.Gateway = types.StringValue(result.Gateway)
	data.HTTPbootID = types.Int64Value(int64(result.HTTPbootID))
	data.IPam = types.StringValue(result.IPam)
	data.Mask = types.StringValue(result.Mask)
	data.Mtu = types.Int64Value(int64(result.Mtu))
	data.NetworkType = types.StringValue(result.NetworkType)
	data.TemplateID = types.Int64Value(int64(result.TemplateID))
	data.TftpID = types.Int64Value(int64(result.TftpID))
	data.To = types.StringValue(result.To)
	data.Vlanid = types.StringValue(result.Vlanid)

	tflog.Trace(ctx, "read subnet data source", map[string]interface{}{"id": data.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
