// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	schema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	generated "github.com/terraform-coop/terraform-provider-foreman/generated"
	"strconv"
)

var _ datasource.DataSource = &templateinputDataSource{}

func NewForemanTemplateInputDataSource() datasource.DataSource {
	return &templateinputDataSource{}
}

type templateinputDataSource struct {
	client *generated.ForemanClient
}

type templateinputDataSourceModel struct {
	ID           types.String `tfsdk:"id"`
	Name         types.String `tfsdk:"name"`
	InputType    types.String `tfsdk:"input_type"`
	Advanced     types.Bool   `tfsdk:"advanced"`
	Default      types.String `tfsdk:"default"`
	Description  types.String `tfsdk:"description"`
	FactName     types.String `tfsdk:"fact_name"`
	HiddenValue  types.Bool   `tfsdk:"hidden_value"`
	Required     types.Bool   `tfsdk:"required"`
	ResourceType types.String `tfsdk:"resource_type"`
	ValueType    types.String `tfsdk:"value_type"`
	VariableName types.String `tfsdk:"variable_name"`
}

func (d *templateinputDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_templateinput"
}

func (d *templateinputDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{Attributes: map[string]schema.Attribute{
		"id": schema.StringAttribute{Computed: true},
		"name": schema.StringAttribute{
			Description: "The name of the templateinput to look up.",
			Required:    true,
		},
	}}
}

func (d *templateinputDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	d.client = client
}

func (d *templateinputDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data templateinputDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	name := data.Name.ValueString()
	result, err := d.client.QueryForemanTemplateInput(ctx, name)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read templateinput, got error: %s", err))
		return
	}
	if result == nil {
		resp.Diagnostics.AddError("Not Found", fmt.Sprintf("ForemanTemplateInput %q not found", name))
		return
	}

	data.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	data.InputType = types.StringValue(result.InputType)
	data.Advanced = types.BoolValue(result.Advanced)
	data.Default = types.StringValue(result.Default)
	data.Description = types.StringValue(result.Description)
	data.FactName = types.StringValue(result.FactName)
	data.HiddenValue = types.BoolValue(result.HiddenValue)
	data.Required = types.BoolValue(result.Required)
	data.ResourceType = types.StringValue(result.ResourceType)
	data.ValueType = types.StringValue(result.ValueType)
	data.VariableName = types.StringValue(result.VariableName)

	tflog.Trace(ctx, "read templateinput data source", map[string]interface{}{"id": data.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
