// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	schema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	generated "github.com/terraform-coop/terraform-provider-foreman/generated"
	"strconv"
)

var _ datasource.DataSource = &subnetDataSource{}

func NewForemanSubnetDataSource() datasource.DataSource {
	return &subnetDataSource{}
}

type subnetDataSource struct {
	client *generated.ForemanClient
}

type subnetDataSourceModel struct {
	ID                types.String `tfsdk:"id"`
	Name              types.String `tfsdk:"name"`
	Network           types.String `tfsdk:"network"`
	BmcID             types.Int64  `tfsdk:"bmc_id"`
	BootMode          types.String `tfsdk:"boot_mode"`
	Cidr              types.String `tfsdk:"cidr"`
	Description       types.String `tfsdk:"description"`
	DhcpID            types.Int64  `tfsdk:"dhcp_id"`
	DNSID             types.Int64  `tfsdk:"dns_id"`
	DNSPrimary        types.String `tfsdk:"dns_primary"`
	DNSSecondary      types.String `tfsdk:"dns_secondary"`
	ExternalipamGroup types.String `tfsdk:"externalipam_group"`
	ExternalipamID    types.Int64  `tfsdk:"externalipam_id"`
	From              types.String `tfsdk:"from"`
	Gateway           types.String `tfsdk:"gateway"`
	HTTPbootID        types.Int64  `tfsdk:"httpboot_id"`
	IPam              types.String `tfsdk:"ipam"`
	Mask              types.String `tfsdk:"mask"`
	Mtu               types.Int64  `tfsdk:"mtu"`
	NetworkType       types.String `tfsdk:"network_type"`
	TemplateID        types.Int64  `tfsdk:"template_id"`
	TftpID            types.Int64  `tfsdk:"tftp_id"`
	To                types.String `tfsdk:"to"`
	Vlanid            types.String `tfsdk:"vlanid"`
}

func (d *subnetDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_subnet"
}

func (d *subnetDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{Attributes: map[string]schema.Attribute{
		"id": schema.StringAttribute{Computed: true},
		"name": schema.StringAttribute{
			Description: "The name of the subnet to look up.",
			Required:    true,
		},
	}}
}

func (d *subnetDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	d.client = client
}

func (d *subnetDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data subnetDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	name := data.Name.ValueString()
	result, err := d.client.QueryForemanSubnet(ctx, name)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read subnet, got error: %s", err))
		return
	}
	if result == nil {
		resp.Diagnostics.AddError("Not Found", fmt.Sprintf("ForemanSubnet %q not found", name))
		return
	}

	data.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	data.Network = types.StringValue(result.Network)
	data.BmcID = types.Int64Value(int64(result.BmcID))
	data.BootMode = types.StringValue(result.BootMode)
	data.Cidr = types.StringValue(result.Cidr)
	data.Description = types.StringValue(result.Description)
	data.DhcpID = types.Int64Value(int64(result.DhcpID))
	data.DNSID = types.Int64Value(int64(result.DNSID))
	data.DNSPrimary = types.StringValue(result.DNSPrimary)
	data.DNSSecondary = types.StringValue(result.DNSSecondary)
	data.ExternalipamGroup = types.StringValue(result.ExternalipamGroup)
	data.ExternalipamID = types.Int64Value(int64(result.ExternalipamID))
	data.From = types.StringValue(result.From)
	data.Gateway = types.StringValue(result.Gateway)
	data.HTTPbootID = types.Int64Value(int64(result.HTTPbootID))
	data.IPam = types.StringValue(result.IPam)
	data.Mask = types.StringValue(result.Mask)
	data.Mtu = types.Int64Value(int64(result.Mtu))
	data.NetworkType = types.StringValue(result.NetworkType)
	data.TemplateID = types.Int64Value(int64(result.TemplateID))
	data.TftpID = types.Int64Value(int64(result.TftpID))
	data.To = types.StringValue(result.To)
	data.Vlanid = types.StringValue(result.Vlanid)

	tflog.Trace(ctx, "read subnet data source", map[string]interface{}{"id": data.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
