// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ datasource.DataSource = &computeresourceDataSource{}
)

func NewForemanComputeResourceDataSource() datasource.DataSource {
	return &computeresourceDataSource{}
}

type computeresourceDataSource struct {
	client *generated.ForemanClient
}

type computeresourceDataSourceModel struct {
	ID                 types.String `tfsdk:"id"`
	Name               types.String `tfsdk:"name"`
	CachingEnabled     types.Bool   `tfsdk:"caching_enabled"`
	Datacenter         types.String `tfsdk:"datacenter"`
	Description        types.String `tfsdk:"description"`
	DisplayType        types.String `tfsdk:"display_type"`
	Domain             types.String `tfsdk:"domain"`
	Password           types.String `tfsdk:"password"`
	ProjectDomainID    types.String `tfsdk:"project_domain_id"`
	ProjectDomainName  types.String `tfsdk:"project_domain_name"`
	Provider           types.String `tfsdk:"provider"`
	Region             types.String `tfsdk:"region"`
	Server             types.String `tfsdk:"server"`
	SetConsolePassword types.Bool   `tfsdk:"set_console_password"`
	Tenant             types.String `tfsdk:"tenant"`
	URL                types.String `tfsdk:"url"`
	User               types.String `tfsdk:"user"`
}

func (d *computeresourceDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_computeresource"
}

func (d *computeresourceDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "The name of the computeresource to look up.",
			},
			"caching_enabled": schema.BoolAttribute{
				Computed:    true,
				Description: "enable caching, for VMware only",
			},
			"datacenter": schema.StringAttribute{
				Computed:    true,
				Description: "for VMware Datacenter",
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"display_type": schema.StringAttribute{
				Computed:    true,
				Description: "for Libvirt only",
			},
			"domain": schema.StringAttribute{
				Computed:    true,
				Description: "for OpenStack (v3) only",
			},
			"password": schema.StringAttribute{
				Computed:    true,
				Description: "Password for EC2, VMware, OpenStack. Secret key for EC2",
			},
			"project_domain_id": schema.StringAttribute{
				Computed:    true,
				Description: "for OpenStack (v3) only",
			},
			"project_domain_name": schema.StringAttribute{
				Computed:    true,
				Description: "for OpenStack (v3) only",
			},
			"provider": schema.StringAttribute{
				Computed:    true,
				Description: "Providers include Libvirt, EC2, Vmware, Openstack",
			},
			"region": schema.StringAttribute{
				Computed:    true,
				Description: "for AzureRm eg. &#39;eastus&#39; and for EC2 only. Use &#39;us-gov-west-1&#39; for EC2 GovCloud region",
			},
			"server": schema.StringAttribute{
				Computed:    true,
				Description: "for VMware",
			},
			"set_console_password": schema.BoolAttribute{
				Computed:    true,
				Description: "for Libvirt and VMware only",
			},
			"tenant": schema.StringAttribute{
				Computed:    true,
				Description: "for OpenStack and AzureRm only",
			},
			"url": schema.StringAttribute{
				Computed:    true,
				Description: "URL for Libvirt and OpenStack",
			},
			"user": schema.StringAttribute{
				Computed:    true,
				Description: "Username for EC2, VMware, OpenStack. Access Key for EC2.",
			},
		},
	}
}

func (d *computeresourceDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	d.client = client
}

func (d *computeresourceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data computeresourceDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	name := data.Name.ValueString()
	result, err := d.client.QueryForemanComputeResource(ctx, name)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read computeresource, got error: %s", err))
		return
	}
	if result == nil {
		resp.Diagnostics.AddError("Not Found", fmt.Sprintf("ForemanComputeResource %q not found", name))
		return
	}

	data.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	data.CachingEnabled = types.BoolValue(result.CachingEnabled)
	data.Datacenter = types.StringValue(result.Datacenter)
	data.Description = types.StringValue(result.Description)
	data.DisplayType = types.StringValue(result.DisplayType)
	data.Domain = types.StringValue(result.Domain)
	data.Password = types.StringValue(result.Password)
	data.ProjectDomainID = types.StringValue(result.ProjectDomainID)
	data.ProjectDomainName = types.StringValue(result.ProjectDomainName)
	data.Provider = types.StringValue(result.Provider)
	data.Region = types.StringValue(result.Region)
	data.Server = types.StringValue(result.Server)
	data.SetConsolePassword = types.BoolValue(result.SetConsolePassword)
	data.Tenant = types.StringValue(result.Tenant)
	data.URL = types.StringValue(result.URL)
	data.User = types.StringValue(result.User)

	tflog.Trace(ctx, "read computeresource data source", map[string]interface{}{"id": data.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
