// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ datasource.DataSource = &webhookDataSource{}
)

func NewForemanWebhookDataSource() datasource.DataSource {
	return &webhookDataSource{}
}

type webhookDataSource struct {
	client *generated.ForemanClient
}

type webhookDataSourceModel struct {
	ID                 types.String `tfsdk:"id"`
	Name               types.String `tfsdk:"name"`
	TargetURL          types.String `tfsdk:"target_url"`
	HTTPMethod         types.String `tfsdk:"http_method"`
	HTTPContentType    types.String `tfsdk:"http_content_type"`
	HTTPHeaders        types.String `tfsdk:"http_headers"`
	Event              types.String `tfsdk:"event"`
	Enabled            types.Bool   `tfsdk:"enabled"`
	VerifySSL          types.Bool   `tfsdk:"verify_ssl"`
	SSLCACerts         types.String `tfsdk:"ssl_ca_certs"`
	ProxyAuthorization types.Bool   `tfsdk:"proxy_authorization"`
	WebhookTemplateID  types.Int64  `tfsdk:"webhook_template_id"`
}

func (d *webhookDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_webhook"
}

func (d *webhookDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "The name of the webhook to look up.",
			},
			"target_url": schema.StringAttribute{
				Computed: true,
			},
			"http_method": schema.StringAttribute{
				Computed: true,
			},
			"http_content_type": schema.StringAttribute{
				Computed: true,
			},
			"http_headers": schema.StringAttribute{
				Computed: true,
			},
			"event": schema.StringAttribute{
				Computed: true,
			},
			"enabled": schema.BoolAttribute{
				Computed: true,
			},
			"verify_ssl": schema.BoolAttribute{
				Computed: true,
			},
			"ssl_ca_certs": schema.StringAttribute{
				Computed: true,
			},
			"proxy_authorization": schema.BoolAttribute{
				Computed: true,
			},
			"webhook_template_id": schema.Int64Attribute{
				Computed: true,
			},
		},
	}
}

func (d *webhookDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	d.client = client
}

func (d *webhookDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data webhookDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	name := data.Name.ValueString()
	result, err := d.client.QueryForemanWebhook(ctx, name)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read webhook, got error: %s", err))
		return
	}
	if result == nil {
		resp.Diagnostics.AddError("Not Found", fmt.Sprintf("ForemanWebhook %q not found", name))
		return
	}

	data.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	data.TargetURL = types.StringValue(result.TargetURL)
	data.HTTPMethod = types.StringValue(result.HTTPMethod)
	data.HTTPContentType = types.StringValue(result.HTTPContentType)
	data.HTTPHeaders = types.StringValue(result.HTTPHeaders)
	data.Event = types.StringValue(result.Event)
	data.Enabled = types.BoolValue(result.Enabled)
	data.VerifySSL = types.BoolValue(result.VerifySSL)
	data.SSLCACerts = types.StringValue(result.SSLCACerts)
	data.ProxyAuthorization = types.BoolValue(result.ProxyAuthorization)
	data.WebhookTemplateID = types.Int64Value(int64(result.WebhookTemplateID))

	tflog.Trace(ctx, "read webhook data source", map[string]interface{}{"id": data.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
