// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ datasource.DataSource = &discovery_ruleDataSource{}
)

func NewForemanDiscoveryRuleDataSource() datasource.DataSource {
	return &discovery_ruleDataSource{}
}

type discovery_ruleDataSource struct {
	client *generated.ForemanClient
}

type discovery_ruleDataSourceModel struct {
	ID                 types.String `tfsdk:"id"`
	Name               types.String `tfsdk:"name"`
	Search             types.String `tfsdk:"search"`
	HostgroupID        types.Int64  `tfsdk:"hostgroup_id"`
	Hostname           types.String `tfsdk:"hostname"`
	HostsLimitMaxCount types.Int64  `tfsdk:"hosts_limit"`
	Priority           types.Int64  `tfsdk:"priority"`
	Enabled            types.Bool   `tfsdk:"enabled"`
}

func (d *discovery_ruleDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_discovery_rule"
}

func (d *discovery_ruleDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "The name of the discovery_rule to look up.",
			},
			"search": schema.StringAttribute{
				Computed: true,
			},
			"hostgroup_id": schema.Int64Attribute{
				Computed: true,
			},
			"hostname": schema.StringAttribute{
				Computed: true,
			},
			"hosts_limit": schema.Int64Attribute{
				Computed: true,
			},
			"priority": schema.Int64Attribute{
				Computed: true,
			},
			"enabled": schema.BoolAttribute{
				Computed: true,
			},
		},
	}
}

func (d *discovery_ruleDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	d.client = client
}

func (d *discovery_ruleDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data discovery_ruleDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	name := data.Name.ValueString()
	result, err := d.client.QueryForemanDiscoveryRule(ctx, name)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read discovery_rule, got error: %s", err))
		return
	}
	if result == nil {
		resp.Diagnostics.AddError("Not Found", fmt.Sprintf("ForemanDiscoveryRule %q not found", name))
		return
	}

	data.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	data.Search = types.StringValue(result.Search)
	data.HostgroupID = types.Int64Value(int64(result.HostgroupID))
	data.Hostname = types.StringValue(result.Hostname)
	data.HostsLimitMaxCount = types.Int64Value(int64(result.HostsLimitMaxCount))
	data.Priority = types.Int64Value(int64(result.Priority))
	data.Enabled = types.BoolValue(result.Enabled)

	tflog.Trace(ctx, "read discovery_rule data source", map[string]interface{}{"id": data.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
