// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ datasource.DataSource = &hostDataSource{}
)

func NewForemanHostDataSource() datasource.DataSource {
	return &hostDataSource{}
}

type hostDataSource struct {
	client *generated.ForemanClient
}

type hostDataSourceModel struct {
	ID                      types.String `tfsdk:"id"`
	Name                    types.String `tfsdk:"name"`
	BmcAvailable            types.Bool   `tfsdk:"bmc_available"`
	BuildStatus             types.Int64  `tfsdk:"build_status"`
	BuildStatusLabel        types.String `tfsdk:"build_status_label"`
	Certname                types.String `tfsdk:"certname"`
	Comment                 types.String `tfsdk:"comment"`
	ComputeResourceProvider types.String `tfsdk:"compute_resource_provider"`
	Creator                 types.String `tfsdk:"creator"`
	CreatorID               types.Int64  `tfsdk:"creator_id"`
	Disk                    types.String `tfsdk:"disk"`
	DisplayName             types.String `tfsdk:"display_name"`
	GlobalStatus            types.Int64  `tfsdk:"global_status"`
	GlobalStatusLabel       types.String `tfsdk:"global_status_label"`
	HostgroupTitle          types.String `tfsdk:"hostgroup_title"`
	InitiatedAt             types.String `tfsdk:"initiated_at"`
	InstalledAt             types.String `tfsdk:"installed_at"`
	IP                      types.String `tfsdk:"ip"`
	IP6                     types.String `tfsdk:"ip6"`
	LastCompile             types.String `tfsdk:"last_compile"`
	LastReport              types.String `tfsdk:"last_report"`
	MAC                     types.String `tfsdk:"mac"`
	OperatingsystemIcon     types.String `tfsdk:"operatingsystem_icon"`
	OwnerName               types.String `tfsdk:"owner_name"`
	Permissions             types.Map    `tfsdk:"permissions"`
	PXELoader               types.String `tfsdk:"pxe_loader"`
	RebuildRequiresPoweroff types.Bool   `tfsdk:"rebuild_requires_poweroff"`
	SpIP                    types.String `tfsdk:"sp_ip"`
	SpMAC                   types.String `tfsdk:"sp_mac"`
	SpName                  types.String `tfsdk:"sp_name"`
	SpSubnetID              types.String `tfsdk:"sp_subnet_id"`
	UseImage                types.String `tfsdk:"use_image"`
}

func (d *hostDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_host"
}

func (d *hostDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "The name of the host to look up.",
			},
			"bmc_available": schema.BoolAttribute{
				Computed: true,
			},
			"build_status": schema.Int64Attribute{
				Computed: true,
			},
			"build_status_label": schema.StringAttribute{
				Computed: true,
			},
			"certname": schema.StringAttribute{
				Computed: true,
			},
			"comment": schema.StringAttribute{
				Computed: true,
			},
			"compute_resource_provider": schema.StringAttribute{
				Computed: true,
			},
			"creator": schema.StringAttribute{
				Computed: true,
			},
			"creator_id": schema.Int64Attribute{
				Computed: true,
			},
			"disk": schema.StringAttribute{
				Computed: true,
			},
			"display_name": schema.StringAttribute{
				Computed: true,
			},
			"global_status": schema.Int64Attribute{
				Computed: true,
			},
			"global_status_label": schema.StringAttribute{
				Computed: true,
			},
			"hostgroup_title": schema.StringAttribute{
				Computed: true,
			},
			"initiated_at": schema.StringAttribute{
				Computed: true,
			},
			"installed_at": schema.StringAttribute{
				Computed: true,
			},
			"ip": schema.StringAttribute{
				Computed: true,
			},
			"ip6": schema.StringAttribute{
				Computed: true,
			},
			"last_compile": schema.StringAttribute{
				Computed: true,
			},
			"last_report": schema.StringAttribute{
				Computed: true,
			},
			"mac": schema.StringAttribute{
				Computed: true,
			},
			"operatingsystem_icon": schema.StringAttribute{
				Computed: true,
			},
			"owner_name": schema.StringAttribute{
				Computed: true,
			},
			"permissions": schema.MapAttribute{
				Computed: true,
			},
			"pxe_loader": schema.StringAttribute{
				Computed: true,
			},
			"rebuild_requires_poweroff": schema.BoolAttribute{
				Computed: true,
			},
			"sp_ip": schema.StringAttribute{
				Computed: true,
			},
			"sp_mac": schema.StringAttribute{
				Computed: true,
			},
			"sp_name": schema.StringAttribute{
				Computed: true,
			},
			"sp_subnet_id": schema.StringAttribute{
				Computed: true,
			},
			"use_image": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

func (d *hostDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	d.client = client
}

func (d *hostDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data hostDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	name := data.Name.ValueString()
	result, err := d.client.QueryForemanHost(ctx, name)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read host, got error: %s", err))
		return
	}
	if result == nil {
		resp.Diagnostics.AddError("Not Found", fmt.Sprintf("ForemanHost %q not found", name))
		return
	}

	data.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	data.BmcAvailable = types.BoolValue(result.BmcAvailable)
	data.BuildStatus = types.Int64Value(int64(result.BuildStatus))
	data.BuildStatusLabel = types.StringValue(result.BuildStatusLabel)
	data.Certname = types.StringValue(result.Certname)
	data.Comment = types.StringValue(result.Comment)
	data.ComputeResourceProvider = types.StringValue(result.ComputeResourceProvider)
	data.Creator = types.StringValue(result.Creator)
	data.CreatorID = types.Int64Value(int64(result.CreatorID))
	data.Disk = types.StringValue(result.Disk)
	data.DisplayName = types.StringValue(result.DisplayName)
	data.GlobalStatus = types.Int64Value(int64(result.GlobalStatus))
	data.GlobalStatusLabel = types.StringValue(result.GlobalStatusLabel)
	data.HostgroupTitle = types.StringValue(result.HostgroupTitle)
	data.InitiatedAt = types.StringValue(result.InitiatedAt)
	data.InstalledAt = types.StringValue(result.InstalledAt)
	data.IP = types.StringValue(result.IP)
	data.IP6 = types.StringValue(result.IP6)
	data.LastCompile = types.StringValue(result.LastCompile)
	data.LastReport = types.StringValue(result.LastReport)
	data.MAC = types.StringValue(result.MAC)
	data.OperatingsystemIcon = types.StringValue(result.OperatingsystemIcon)
	data.OwnerName = types.StringValue(result.OwnerName)
	data.PXELoader = types.StringValue(result.PXELoader)
	data.RebuildRequiresPoweroff = types.BoolValue(result.RebuildRequiresPoweroff)
	data.SpIP = types.StringValue(result.SpIP)
	data.SpMAC = types.StringValue(result.SpMAC)
	data.SpName = types.StringValue(result.SpName)
	data.SpSubnetID = types.StringValue(result.SpSubnetID)
	data.UseImage = types.StringValue(result.UseImage)

	tflog.Trace(ctx, "read host data source", map[string]interface{}{"id": data.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
