// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsdchema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ datasource.DataSource = &parameterDataSource{}
)

func NewForemanParameterDataSource() datasource.DataSource {
	return &parameterDataSource{}
}

type parameterDataSource struct {
	client *generated.ForemanClient
}

type parameterDataSourceModel struct {
	ID            types.String `tfsdk:"id"`
	Name          types.String `tfsdk:"name"`
	ParameterType types.String `tfsdk:"parameter_type"`
	Value         types.String `tfsdk:"value"`
	HiddenValue   types.Bool   `tfsdk:"hidden_value"`
}

func (d *parameterDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_parameter"
}

func (d *parameterDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsdchema.Schema{
		Attributes: map[string]dsdchema.Attribute{
			"id": dsdchema.StringAttribute{
				Computed: true,
			},
			"name": dsdchema.StringAttribute{
				Required:    true,
				Description: "The name of the parameter to look up.",
			},
			"parameter_type": dsdchema.StringAttribute{
				Computed:    true,
				Description: "Type of value",
			},
			"value": dsdchema.StringAttribute{
				Computed: true,
			},
			"hidden_value": dsdchema.BoolAttribute{
				Computed:    true,
				Description: "Should the value be hidden",
			},
		},
	}
}

func (d *parameterDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	d.client = client
}

func (d *parameterDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data parameterDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	name := data.Name.ValueString()
	result, err := d.client.QueryForemanParameter(ctx, name)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read parameter, got error: %s", err))
		return
	}
	if result == nil {
		resp.Diagnostics.AddError("Not Found", fmt.Sprintf("ForemanParameter %q not found", name))
		return
	}

	data.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	data.ParameterType = types.StringValue(result.ParameterType)
	data.Value = types.StringValue(result.Value)
	data.HiddenValue = types.BoolValue(result.HiddenValue)

	tflog.Trace(ctx, "read parameter data source", map[string]interface{}{"id": data.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
