// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ datasource.DataSource = &hostgroupDataSource{}
)

func NewForemanHostgroupDataSource() datasource.DataSource {
	return &hostgroupDataSource{}
}

type hostgroupDataSource struct {
	client *generated.ForemanClient
}

type hostgroupDataSourceModel struct {
	ID                types.String `tfsdk:"id"`
	Name              types.String `tfsdk:"name"`
	ArchitectureID    types.Int64  `tfsdk:"architecture_id"`
	ComputeProfileID  types.Int64  `tfsdk:"compute_profile_id"`
	Description       types.String `tfsdk:"description"`
	DomainID          types.Int64  `tfsdk:"domain_id"`
	MediumID          types.Int64  `tfsdk:"medium_id"`
	OperatingsystemID types.Int64  `tfsdk:"operatingsystem_id"`
	ParentID          types.String `tfsdk:"parent_id"`
	PtableID          types.Int64  `tfsdk:"ptable_id"`
	PXELoader         types.String `tfsdk:"pxe_loader"`
	RealmID           types.String `tfsdk:"realm_id"`
	Subnet6ID         types.Int64  `tfsdk:"subnet6_id"`
	SubnetID          types.Int64  `tfsdk:"subnet_id"`
}

func (d *hostgroupDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_hostgroup"
}

func (d *hostgroupDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "The name of the hostgroup to look up.",
			},
			"architecture_id": schema.Int64Attribute{
				Computed: true,
			},
			"compute_profile_id": schema.Int64Attribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"domain_id": schema.Int64Attribute{
				Computed: true,
			},
			"medium_id": schema.Int64Attribute{
				Computed: true,
			},
			"operatingsystem_id": schema.Int64Attribute{
				Computed: true,
			},
			"parent_id": schema.StringAttribute{
				Computed: true,
			},
			"ptable_id": schema.Int64Attribute{
				Computed: true,
			},
			"pxe_loader": schema.StringAttribute{
				Computed: true,
			},
			"realm_id": schema.StringAttribute{
				Computed: true,
			},
			"subnet6_id": schema.Int64Attribute{
				Computed: true,
			},
			"subnet_id": schema.Int64Attribute{
				Computed: true,
			},
		},
	}
}

func (d *hostgroupDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	d.client = client
}

func (d *hostgroupDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data hostgroupDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	name := data.Name.ValueString()
	result, err := d.client.QueryForemanHostgroup(ctx, name)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read hostgroup, got error: %s", err))
		return
	}
	if result == nil {
		resp.Diagnostics.AddError("Not Found", fmt.Sprintf("ForemanHostgroup %q not found", name))
		return
	}

	data.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	data.ArchitectureID = types.Int64Value(int64(result.ArchitectureID))
	data.ComputeProfileID = types.Int64Value(int64(result.ComputeProfileID))
	data.Description = types.StringValue(result.Description)
	data.DomainID = types.Int64Value(int64(result.DomainID))
	data.MediumID = types.Int64Value(int64(result.MediumID))
	data.OperatingsystemID = types.Int64Value(int64(result.OperatingsystemID))
	data.ParentID = types.StringValue(result.ParentID)
	data.PtableID = types.Int64Value(int64(result.PtableID))
	data.PXELoader = types.StringValue(result.PXELoader)
	data.RealmID = types.StringValue(result.RealmID)
	data.Subnet6ID = types.Int64Value(int64(result.Subnet6ID))
	data.SubnetID = types.Int64Value(int64(result.SubnetID))

	tflog.Trace(ctx, "read hostgroup data source", map[string]interface{}{"id": data.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
