// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsdchema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ datasource.DataSource = &defaulttemplateDataSource{}
)

func NewForemanDefaultTemplateDataSource() datasource.DataSource {
	return &defaulttemplateDataSource{}
}

type defaulttemplateDataSource struct {
	client *generated.ForemanClient
}

type defaulttemplateDataSourceModel struct {
	ID                     types.String `tfsdk:"id"`
	Name                   types.String `tfsdk:"name"`
	ProvisioningTemplateID types.Int64  `tfsdk:"provisioning_template_id"`
	TemplateKindID         types.Int64  `tfsdk:"template_kind_id"`
}

func (d *defaulttemplateDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_defaulttemplate"
}

func (d *defaulttemplateDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsdchema.Schema{
		Attributes: map[string]dsdchema.Attribute{
			"id": dsdchema.StringAttribute{
				Computed: true,
			},
			"name": dsdchema.StringAttribute{
				Required:    true,
				Description: "The name of the defaulttemplate to look up.",
			},
			"provisioning_template_id": dsdchema.Int64Attribute{
				Computed:    true,
				Description: "ID of provisioning template",
			},
			"template_kind_id": dsdchema.Int64Attribute{
				Computed: true,
			},
		},
	}
}

func (d *defaulttemplateDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	d.client = client
}

func (d *defaulttemplateDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data defaulttemplateDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	name := data.Name.ValueString()
	result, err := d.client.QueryForemanDefaultTemplate(ctx, name)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read defaulttemplate, got error: %s", err))
		return
	}
	if result == nil {
		resp.Diagnostics.AddError("Not Found", fmt.Sprintf("ForemanDefaultTemplate %q not found", name))
		return
	}

	data.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	data.ProvisioningTemplateID = types.Int64Value(int64(result.ProvisioningTemplateID))
	data.TemplateKindID = types.Int64Value(int64(result.TemplateKindID))

	tflog.Trace(ctx, "read defaulttemplate data source", map[string]interface{}{"id": data.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
