// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsdchema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ datasource.DataSource = &operatingsystemDataSource{}
)

func NewForemanOperatingSystemDataSource() datasource.DataSource {
	return &operatingsystemDataSource{}
}

type operatingsystemDataSource struct {
	client *generated.ForemanClient
}

type operatingsystemDataSourceModel struct {
	ID           types.String `tfsdk:"id"`
	Name         types.String `tfsdk:"name"`
	Major        types.String `tfsdk:"major"`
	Description  types.String `tfsdk:"description"`
	Family       types.String `tfsdk:"family"`
	Minor        types.String `tfsdk:"minor"`
	PasswordHash types.String `tfsdk:"password_hash"`
	ReleaseName  types.String `tfsdk:"release_name"`
}

func (d *operatingsystemDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_operatingsystem"
}

func (d *operatingsystemDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsdchema.Schema{
		Attributes: map[string]dsdchema.Attribute{
			"id": dsdchema.StringAttribute{
				Computed: true,
			},
			"name": dsdchema.StringAttribute{
				Required:    true,
				Description: "The name of the operatingsystem to look up.",
			},
			"major": dsdchema.StringAttribute{
				Computed: true,
			},
			"description": dsdchema.StringAttribute{
				Computed: true,
			},
			"family": dsdchema.StringAttribute{
				Computed: true,
			},
			"minor": dsdchema.StringAttribute{
				Computed: true,
			},
			"password_hash": dsdchema.StringAttribute{
				Computed:    true,
				Description: "Root password hash function to use",
			},
			"release_name": dsdchema.StringAttribute{
				Computed: true,
			},
		},
	}
}

func (d *operatingsystemDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	d.client = client
}

func (d *operatingsystemDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data operatingsystemDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	name := data.Name.ValueString()
	result, err := d.client.QueryForemanOperatingSystem(ctx, name)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read operatingsystem, got error: %s", err))
		return
	}
	if result == nil {
		resp.Diagnostics.AddError("Not Found", fmt.Sprintf("ForemanOperatingSystem %q not found", name))
		return
	}

	data.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	data.Major = types.StringValue(result.Major)
	data.Description = types.StringValue(result.Description)
	data.Family = types.StringValue(result.Family)
	data.Minor = types.StringValue(result.Minor)
	data.PasswordHash = types.StringValue(result.PasswordHash)
	data.ReleaseName = types.StringValue(result.ReleaseName)

	tflog.Trace(ctx, "read operatingsystem data source", map[string]interface{}{"id": data.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
