// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	datasource "github.com/hashicorp/terraform-plugin-framework/datasource"
	provider "github.com/hashicorp/terraform-plugin-framework/provider"
	schema "github.com/hashicorp/terraform-plugin-framework/provider/schema"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	generated "github.com/terraform-coop/terraform-provider-foreman/generated"
	"net/url"
	"os"
)

var _ provider.Provider = &ForemanProvider{}

type ForemanProvider struct {
	version string
}

type ForemanProviderModel struct {
	ServerHostname      types.String `tfsdk:"server_hostname"`
	ServerProtocol      types.String `tfsdk:"server_protocol"`
	ClientUsername      types.String `tfsdk:"client_username"`
	ClientPassword      types.String `tfsdk:"client_password"`
	ClientTLSInsecure   types.Bool   `tfsdk:"client_tls_insecure"`
	ClientAuthNegotiate types.Bool   `tfsdk:"client_auth_negotiate"`
	OrganizationID      types.Int64  `tfsdk:"organization_id"`
	LocationID          types.Int64  `tfsdk:"location_id"`
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &ForemanProvider{version: version}
	}
}

func (p *ForemanProvider) Metadata(_ context.Context, _ provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "foreman"
	resp.Version = p.version
}

func (p *ForemanProvider) Schema(_ context.Context, _ provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{Attributes: map[string]schema.Attribute{
		"client_auth_negotiate": schema.BoolAttribute{
			Description: "Use HTTP negotiate auth. Defaults to false.",
			Optional:    true,
		},
		"client_password": schema.StringAttribute{
			Description: "Password. Can also be set via FOREMAN_CLIENT_PASSWORD.",
			Optional:    true,
			Sensitive:   true,
		},
		"client_tls_insecure": schema.BoolAttribute{
			Description: "Skip TLS verification. Defaults to false.",
			Optional:    true,
		},
		"client_username": schema.StringAttribute{
			Description: "Username. Can also be set via FOREMAN_CLIENT_USERNAME.",
			Optional:    true,
		},
		"location_id": schema.Int64Attribute{
			Description: "Location for all API calls. Defaults to 0.",
			Optional:    true,
		},
		"organization_id": schema.Int64Attribute{
			Description: "Organization for all API calls. Defaults to 0.",
			Optional:    true,
		},
		"server_hostname": schema.StringAttribute{
			Description: "The hostname / IP address of the Foreman REST API server",
			Required:    true,
		},
		"server_protocol": schema.StringAttribute{
			Description: "The protocol. Defaults to https.",
			Optional:    true,
		},
	}}
}

func (p *ForemanProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var config ForemanProviderModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	hostname := config.ServerHostname.ValueString()
	if hostname == "" {
		resp.Diagnostics.AddError("Missing server_hostname", "Set server_hostname in your provider config.")
		return
	}

	protocol := "https"
	if !config.ServerProtocol.IsNull() && !config.ServerProtocol.IsUnknown() {
		protocol = config.ServerProtocol.ValueString()
	}

	username := ""
	if !config.ClientUsername.IsNull() && !config.ClientUsername.IsUnknown() {
		username = config.ClientUsername.ValueString()
	} else if v := os.Getenv("FOREMAN_CLIENT_USERNAME"); v != "" {
		username = v
	}

	password := ""
	if !config.ClientPassword.IsNull() && !config.ClientPassword.IsUnknown() {
		password = config.ClientPassword.ValueString()
	} else if v := os.Getenv("FOREMAN_CLIENT_PASSWORD"); v != "" {
		password = v
	}

	tlsInsecure := false
	if !config.ClientTLSInsecure.IsNull() && !config.ClientTLSInsecure.IsUnknown() {
		tlsInsecure = config.ClientTLSInsecure.ValueBool()
	}

	negotiateAuth := false
	if !config.ClientAuthNegotiate.IsNull() && !config.ClientAuthNegotiate.IsUnknown() {
		negotiateAuth = config.ClientAuthNegotiate.ValueBool()
	}

	var orgID, locID int64
	if !config.OrganizationID.IsNull() && !config.OrganizationID.IsUnknown() {
		orgID = config.OrganizationID.ValueInt64()
	}
	if !config.LocationID.IsNull() && !config.LocationID.IsUnknown() {
		locID = config.LocationID.ValueInt64()
	}

	client := generated.NewClient(url.URL{
		Host:   hostname,
		Scheme: protocol,
	}, generated.ClientCredentials{
		Password: password,
		Username: username,
	}, generated.ClientConfig{
		LocationID:     int(locID),
		NegotiateAuth:  negotiateAuth,
		OrganizationID: int(orgID),
		TLSInsecure:    tlsInsecure,
	})

	resp.DataSourceData = client
	resp.ResourceData = client
}

func (p *ForemanProvider) Resources(_ context.Context) []func() resource.Resource {
	// Katello resources are not in the pinned core apidoc/v2.json, so they
	// are registered explicitly here. Keep in sync with generated/katello_*.go.
	return []func() resource.Resource{NewForemanArchitectureResource, NewForemanAutosignResource, NewForemanCommonParameterResource, NewForemanComputeProfileResource, NewForemanComputeResourceResource, NewForemanDefaultTemplateResource, NewForemanDomainResource, NewForemanHTTPProxyResource, NewForemanHostResource, NewForemanHostgroupResource, NewForemanImageResource, NewForemanMediumResource, NewForemanModelResource, NewForemanOperatingSystemResource, NewForemanParameterResource, NewForemanPartitionTableResource, NewForemanProvisioningTemplateResource, NewForemanRealmResource, NewForemanSettingResource, NewForemanSmartProxyResource, NewForemanSubnetResource, NewForemanTemplateInputResource, NewForemanUserResource, NewForemanUsergroupResource, NewForemanEnvironmentResource, NewForemanJobTemplateResource, NewForemanPuppetClassResource, NewForemanSmartClassParameterResource, NewForemanTemplateKindResource, NewForemanDiscoveryRuleResource, NewForemanWebhookResource, NewForemanWebhookTemplateResource, NewForemanOverrideValueResource, NewKatelloContentCredentialResource, NewKatelloContentViewResource, NewKatelloLifecycleEnvironmentResource, NewKatelloProductResource, NewKatelloRepositoryResource, NewKatelloSyncPlanResource}
}

func (p *ForemanProvider) DataSources(_ context.Context) []func() datasource.DataSource {
	// Katello data sources are not in the pinned core apidoc/v2.json.
	return []func() datasource.DataSource{NewForemanArchitectureDataSource, NewForemanAutosignDataSource, NewForemanCommonParameterDataSource, NewForemanComputeProfileDataSource, NewForemanComputeResourceDataSource, NewForemanDefaultTemplateDataSource, NewForemanDomainDataSource, NewForemanHTTPProxyDataSource, NewForemanHostDataSource, NewForemanHostgroupDataSource, NewForemanImageDataSource, NewForemanMediumDataSource, NewForemanModelDataSource, NewForemanOperatingSystemDataSource, NewForemanParameterDataSource, NewForemanPartitionTableDataSource, NewForemanProvisioningTemplateDataSource, NewForemanRealmDataSource, NewForemanSettingDataSource, NewForemanSmartProxyDataSource, NewForemanSubnetDataSource, NewForemanTemplateInputDataSource, NewForemanUserDataSource, NewForemanUsergroupDataSource, NewForemanEnvironmentDataSource, NewForemanJobTemplateDataSource, NewForemanPuppetClassDataSource, NewForemanSmartClassParameterDataSource, NewForemanTemplateKindDataSource, NewForemanDiscoveryRuleDataSource, NewForemanWebhookDataSource, NewForemanWebhookTemplateDataSource, NewKatelloContentCredentialDataSource, NewKatelloContentViewDataSource, NewKatelloLifecycleEnvironmentDataSource, NewKatelloProductDataSource, NewKatelloRepositoryDataSource, NewKatelloSyncPlanDataSource}
}
