// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &katelloRepositoryResource{}
	_ resource.ResourceWithImportState = &katelloRepositoryResource{}
)

func NewKatelloRepositoryResource() resource.Resource {
	return &katelloRepositoryResource{}
}

type katelloRepositoryResource struct {
	client *generated.ForemanClient
}

type katelloRepositoryResourceModel struct {
	ID                  types.String `tfsdk:"id"`
	Name                types.String `tfsdk:"name"`
	Description         types.String `tfsdk:"description"`
	Label               types.String `tfsdk:"label"`
	ProductID           types.Int64  `tfsdk:"product_id"`
	ContentType         types.String `tfsdk:"content_type"`
	URL                 types.String `tfsdk:"url"`
	GpgKeyID            types.Int64  `tfsdk:"gpg_key_id"`
	Unprotected         types.Bool   `tfsdk:"unprotected"`
	ChecksumType        types.String `tfsdk:"checksum_type"`
	DownloadPolicy      types.String `tfsdk:"download_policy"`
	DownloadConcurrency types.Int64  `tfsdk:"download_concurrency"`
	MirrorOnSync        types.Bool   `tfsdk:"mirror_on_sync"`
	MirroringPolicy     types.String `tfsdk:"mirroring_policy"`
	HttpProxyPolicy     types.String `tfsdk:"http_proxy_policy"`
	HttpProxyID         types.Int64  `tfsdk:"http_proxy_id"`
}

func (r *katelloRepositoryResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_katello_repository"
}

func (r *katelloRepositoryResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"description": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"label": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"product_id": schema.Int64Attribute{
				Required: false,
				Optional: true,
			},
			"content_type": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"url": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"gpg_key_id": schema.Int64Attribute{
				Required: false,
				Optional: true,
			},
			"unprotected": schema.BoolAttribute{
				Required: false,
				Optional: true,
			},
			"checksum_type": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"download_policy": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"download_concurrency": schema.Int64Attribute{
				Required: false,
				Optional: true,
				PlanModifiers: []planmodifier.Int64{
					suppressDownloadConcurrencyDiff{},
				},
			},
			"mirror_on_sync": schema.BoolAttribute{
				Required: false,
				Optional: true,
			},
			"mirroring_policy": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"http_proxy_policy": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"http_proxy_id": schema.Int64Attribute{
				Required: false,
				Optional: true,
			},
		},
	}
}

func (r *katelloRepositoryResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}

func (r *katelloRepositoryResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan katelloRepositoryResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanKatelloRepositoryRequest{
		Name:                plan.Name.ValueString(),
		Description:         plan.Description.ValueString(),
		Label:               plan.Label.ValueString(),
		ProductID:           int(plan.ProductID.ValueInt64()),
		ContentType:         plan.ContentType.ValueString(),
		URL:                 plan.URL.ValueString(),
		GpgKeyID:            int(plan.GpgKeyID.ValueInt64()),
		Unprotected:         plan.Unprotected.ValueBool(),
		ChecksumType:        plan.ChecksumType.ValueString(),
		DownloadPolicy:      plan.DownloadPolicy.ValueString(),
		DownloadConcurrency: int(plan.DownloadConcurrency.ValueInt64()),
		MirrorOnSync:        plan.MirrorOnSync.ValueBool(),
		MirroringPolicy:     plan.MirroringPolicy.ValueString(),
		HttpProxyPolicy:     plan.HttpProxyPolicy.ValueString(),
		HttpProxyID:         int(plan.HttpProxyID.ValueInt64()),
	}

	result, err := r.client.CreateForemanKatelloRepository(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create katello repository, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.Name = types.StringValue(result.Name)
	plan.Description = types.StringValue(result.Description)
	plan.Label = types.StringValue(result.Label)
	plan.ProductID = types.Int64Value(int64(result.ProductID))
	plan.ContentType = types.StringValue(result.ContentType)
	plan.URL = types.StringValue(result.URL)
	plan.GpgKeyID = types.Int64Value(int64(result.GpgKeyID))
	plan.Unprotected = types.BoolValue(result.Unprotected)
	plan.ChecksumType = types.StringValue(result.ChecksumType)
	plan.DownloadPolicy = types.StringValue(result.DownloadPolicy)
	plan.DownloadConcurrency = types.Int64Value(int64(result.DownloadConcurrency))
	plan.MirrorOnSync = types.BoolValue(result.MirrorOnSync)
	plan.MirroringPolicy = types.StringValue(result.MirroringPolicy)
	plan.HttpProxyPolicy = types.StringValue(result.HttpProxyPolicy)
	plan.HttpProxyID = types.Int64Value(int64(result.HttpProxyID))

	tflog.Trace(ctx, "created katello repository", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *katelloRepositoryResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state katelloRepositoryResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanKatelloRepository(ctx, id)
	if err != nil {
		if generated.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read katello repository, got error: %s", err))
		return
	}
	state.Name = types.StringValue(result.Name)
	state.Description = types.StringValue(result.Description)
	state.Label = types.StringValue(result.Label)
	state.ProductID = types.Int64Value(int64(result.ProductID))
	state.ContentType = types.StringValue(result.ContentType)
	state.URL = types.StringValue(result.URL)
	state.GpgKeyID = types.Int64Value(int64(result.GpgKeyID))
	state.Unprotected = types.BoolValue(result.Unprotected)
	state.ChecksumType = types.StringValue(result.ChecksumType)
	state.DownloadPolicy = types.StringValue(result.DownloadPolicy)
	state.DownloadConcurrency = types.Int64Value(int64(result.DownloadConcurrency))
	state.MirrorOnSync = types.BoolValue(result.MirrorOnSync)
	state.MirroringPolicy = types.StringValue(result.MirroringPolicy)
	state.HttpProxyPolicy = types.StringValue(result.HttpProxyPolicy)
	state.HttpProxyID = types.Int64Value(int64(result.HttpProxyID))

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *katelloRepositoryResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan katelloRepositoryResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanKatelloRepositoryRequest{
		Name:                plan.Name.ValueString(),
		Description:         plan.Description.ValueString(),
		Label:               plan.Label.ValueString(),
		ProductID:           int(plan.ProductID.ValueInt64()),
		ContentType:         plan.ContentType.ValueString(),
		URL:                 plan.URL.ValueString(),
		GpgKeyID:            int(plan.GpgKeyID.ValueInt64()),
		Unprotected:         plan.Unprotected.ValueBool(),
		ChecksumType:        plan.ChecksumType.ValueString(),
		DownloadPolicy:      plan.DownloadPolicy.ValueString(),
		DownloadConcurrency: int(plan.DownloadConcurrency.ValueInt64()),
		MirrorOnSync:        plan.MirrorOnSync.ValueBool(),
		MirroringPolicy:     plan.MirroringPolicy.ValueString(),
		HttpProxyPolicy:     plan.HttpProxyPolicy.ValueString(),
		HttpProxyID:         int(plan.HttpProxyID.ValueInt64()),
	}

	result, err := r.client.UpdateForemanKatelloRepository(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update katello repository, got error: %s", err))
		return
	}
	plan.Name = types.StringValue(result.Name)
	plan.Description = types.StringValue(result.Description)
	plan.Label = types.StringValue(result.Label)
	plan.ProductID = types.Int64Value(int64(result.ProductID))
	plan.ContentType = types.StringValue(result.ContentType)
	plan.URL = types.StringValue(result.URL)
	plan.GpgKeyID = types.Int64Value(int64(result.GpgKeyID))
	plan.Unprotected = types.BoolValue(result.Unprotected)
	plan.ChecksumType = types.StringValue(result.ChecksumType)
	plan.DownloadPolicy = types.StringValue(result.DownloadPolicy)
	plan.DownloadConcurrency = types.Int64Value(int64(result.DownloadConcurrency))
	plan.MirrorOnSync = types.BoolValue(result.MirrorOnSync)
	plan.MirroringPolicy = types.StringValue(result.MirroringPolicy)
	plan.HttpProxyPolicy = types.StringValue(result.HttpProxyPolicy)
	plan.HttpProxyID = types.Int64Value(int64(result.HttpProxyID))

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *katelloRepositoryResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state katelloRepositoryResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	err = r.client.DeleteForemanKatelloRepository(ctx, id)
	if err != nil && !generated.IsNotFoundError(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete katello repository, got error: %s", err))
		return
	}
}

func (r *katelloRepositoryResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
