// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	schema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	planmodifier "github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	stringplanmodifier "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	generated "github.com/terraform-coop/terraform-provider-foreman/generated"
	"strconv"
)

var _ resource.Resource = &smartclassparameterResource{}
var _ resource.ResourceWithImportState = &smartclassparameterResource{}

func NewForemanSmartClassParameterResource() resource.Resource {
	return &smartclassparameterResource{}
}

type smartclassparameterResource struct {
	client *generated.ForemanClient
}

type smartclassparameterResourceModel struct {
	ID            types.String `tfsdk:"id"`
	Parameter     types.String `tfsdk:"parameter"`
	PuppetclassID types.Int64  `tfsdk:"puppetclass_id"`
	Override      types.Bool   `tfsdk:"override"`
	Description   types.String `tfsdk:"description"`
	DefaultValue  types.String `tfsdk:"default_value"`
	HiddenValue   types.Bool   `tfsdk:"hidden_value"`
}

func (r *smartclassparameterResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_smartclassparameter"
}

func (r *smartclassparameterResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{Attributes: map[string]schema.Attribute{
		"default_value": schema.StringAttribute{Computed: true},
		"description":   schema.StringAttribute{Computed: true},
		"hidden_value":  schema.BoolAttribute{Computed: true},
		"id": schema.StringAttribute{
			Computed:      true,
			PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
		},
		"override":       schema.BoolAttribute{Computed: true},
		"parameter":      schema.StringAttribute{Computed: true},
		"puppetclass_id": schema.Int64Attribute{Computed: true},
	}}
}

func (r *smartclassparameterResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}

func (r *smartclassparameterResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	tflog.Warn(ctx, "Create is not supported for smartclassparameter")
	resp.Diagnostics.AddError("Not Supported", "Create is not supported for this resource")
}

func (r *smartclassparameterResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state smartclassparameterResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanSmartClassParameter(ctx, id)
	if err != nil {
		if generated.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read smartclassparameter, got error: %s", err))
		return
	}

	state.Parameter = types.StringValue(result.Parameter)
	state.PuppetclassID = types.Int64Value(int64(result.PuppetclassID))
	state.Override = types.BoolValue(result.Override)
	state.Description = types.StringValue(result.Description)
	state.DefaultValue = types.StringValue(result.DefaultValue)
	state.HiddenValue = types.BoolValue(result.HiddenValue)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *smartclassparameterResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan smartclassparameterResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanSmartClassParameterRequest{}

	result, err := r.client.UpdateForemanSmartClassParameter(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update smartclassparameter, got error: %s", err))
		return
	}

	plan.Parameter = types.StringValue(result.Parameter)
	plan.PuppetclassID = types.Int64Value(int64(result.PuppetclassID))
	plan.Override = types.BoolValue(result.Override)
	plan.Description = types.StringValue(result.Description)
	plan.DefaultValue = types.StringValue(result.DefaultValue)
	plan.HiddenValue = types.BoolValue(result.HiddenValue)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *smartclassparameterResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	tflog.Warn(ctx, "Delete is not supported for smartclassparameter")
	resp.Diagnostics.AddError("Not Supported", "Delete is not supported for this resource")
}

func (r *smartclassparameterResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
