// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	attr "github.com/hashicorp/terraform-plugin-framework/attr"
	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	schema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	planmodifier "github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	stringplanmodifier "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	generated "github.com/terraform-coop/terraform-provider-foreman/generated"
	"strconv"
)

var _ resource.Resource = &mediaResource{}
var _ resource.ResourceWithImportState = &mediaResource{}

func NewForemanMediumResource() resource.Resource {
	return &mediaResource{}
}

type mediaResource struct {
	client *generated.ForemanClient
}

type mediaResourceModel struct {
	ID                 types.String `tfsdk:"id"`
	Name               types.String `tfsdk:"name"`
	Path               types.String `tfsdk:"path"`
	OperatingsystemIDs types.List   `tfsdk:"operatingsystem_ids"`
	OsFamily           types.String `tfsdk:"os_family"`
}

func (r *mediaResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_media"
}

func (r *mediaResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{Attributes: map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:      true,
			PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
		},
		"name": schema.StringAttribute{
			Description: "Name of media",
			Required:    true,
		},
		"operatingsystem_ids": schema.ListAttribute{
			ElementType: types.Int64Type,
			Optional:    true,
			Required:    false,
		},
		"os_family": schema.StringAttribute{
			Description: "Operating system family, available values: AIX, Altlinux, Archlinux, Coreos, Debian, Fcos, Freebsd, Gentoo, Junos, NXOS, Rancheros, Redhat, Rhcos, Solaris, Suse, VRP, Windows, Xenserver",
			Optional:    true,
			Required:    false,
		},
		"path": schema.StringAttribute{
			Description: "The path to the medium, can be a URL or a valid NFS server (exclusive of the architecture).  for example mirror.centos.org/centos/$version/os/$arch where $arch will be substituted for the host&#39;s actual OS architecture and $version, $major and $minor will be substituted for the version of the operating system.  Solaris and Debian media may also use $release.",
			Required:    true,
		},
	}}
}

func (r *mediaResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}

func (r *mediaResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan mediaResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanMediumRequest{
		Name: plan.Name.ValueString(),
		OperatingsystemIDs: func() []int64 {
			if plan.OperatingsystemIDs.IsNull() || plan.OperatingsystemIDs.IsUnknown() {
				return nil
			}
			var ids []int64
			for _, v := range plan.OperatingsystemIDs.Elements() {
				if iv, ok := v.(types.Int64); ok {
					ids = append(ids, iv.ValueInt64())
				}
			}
			return ids
		}(),
		OsFamily: plan.OsFamily.ValueString(),
		Path:     plan.Path.ValueString(),
	}

	result, err := r.client.CreateForemanMedium(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create media, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.Name = types.StringValue(result.Name)
	plan.Path = types.StringValue(result.Path)
	plan.OsFamily = types.StringValue(result.OsFamily)

	tflog.Trace(ctx, "created media", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mediaResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state mediaResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanMedium(ctx, id)
	if err != nil {
		if generated.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read media, got error: %s", err))
		return
	}

	state.Name = types.StringValue(result.Name)
	state.Path = types.StringValue(result.Path)
	if result.OperatingsystemIDs != nil {
		elems := make([]attr.Value, len(result.OperatingsystemIDs))
		for i, v := range result.OperatingsystemIDs {
			elems[i] = types.Int64Value(int64(v))
		}
		state.OperatingsystemIDs = types.ListValueMust(types.Int64Type, elems)
	} else {
		state.OperatingsystemIDs = types.ListNull(types.Int64Type)
	}
	state.OsFamily = types.StringValue(result.OsFamily)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *mediaResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan mediaResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanMediumRequest{
		Name: plan.Name.ValueString(),
		OperatingsystemIDs: func() []int64 {
			if plan.OperatingsystemIDs.IsNull() || plan.OperatingsystemIDs.IsUnknown() {
				return nil
			}
			var ids []int64
			for _, v := range plan.OperatingsystemIDs.Elements() {
				if iv, ok := v.(types.Int64); ok {
					ids = append(ids, iv.ValueInt64())
				}
			}
			return ids
		}(),
		OsFamily: plan.OsFamily.ValueString(),
		Path:     plan.Path.ValueString(),
	}

	result, err := r.client.UpdateForemanMedium(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update media, got error: %s", err))
		return
	}

	plan.Name = types.StringValue(result.Name)
	plan.Path = types.StringValue(result.Path)
	plan.OsFamily = types.StringValue(result.OsFamily)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mediaResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state mediaResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	err = r.client.DeleteForemanMedium(ctx, id)
	if err != nil && !generated.IsNotFoundError(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete media, got error: %s", err))
		return
	}
}

func (r *mediaResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
