// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-coop/terraform-provider-foreman/generated"
)

var (
	_ resource.Resource                = &provisioningtemplateResource{}
	_ resource.ResourceWithImportState = &provisioningtemplateResource{}
)

func NewForemanProvisioningTemplateResource() resource.Resource {
	return &provisioningtemplateResource{}
}

type provisioningtemplateResource struct {
	client *generated.ForemanClient
}

type provisioningtemplateResourceModel struct {
	ID                             types.String `tfsdk:"id"`
	Name                           types.String `tfsdk:"name"`
	Template                       types.String `tfsdk:"template"`
	AuditComment                   types.String `tfsdk:"audit_comment"`
	Description                    types.String `tfsdk:"description"`
	Locked                         types.Bool   `tfsdk:"locked"`
	OperatingsystemIDs             types.List   `tfsdk:"operatingsystem_ids"`
	Snippet                        types.Bool   `tfsdk:"snippet"`
	TemplateCombinationsAttributes types.List   `tfsdk:"template_combinations_attributes"`
	TemplateKindID                 types.Int64  `tfsdk:"template_kind_id"`
}

func (r *provisioningtemplateResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_provisioningtemplate"
}

func (r *provisioningtemplateResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "template name",
			},
			"template": schema.StringAttribute{
				Required: true,
			},
			"audit_comment": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"description": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"locked": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Whether or not the template is locked for editing",
			},
			"operatingsystem_ids": schema.ListAttribute{
				Required:    false,
				Optional:    true,
				Description: "Array of operating system IDs to associate with the template",
				ElementType: types.Int64Type,
			},
			"snippet": schema.BoolAttribute{
				Required: false,
				Optional: true,
			},
			"template_combinations_attributes": schema.ListAttribute{
				Required:    false,
				Optional:    true,
				Description: "Array of template combinations (hostgroup_id, environment_id)",
				ElementType: types.Int64Type,
			},
			"template_kind_id": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Description: "not relevant for snippet",
			},
		},
	}
}

func (r *provisioningtemplateResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}
func (r *provisioningtemplateResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan provisioningtemplateResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanProvisioningTemplateRequest{
		Name:         plan.Name.ValueString(),
		Template:     plan.Template.ValueString(),
		AuditComment: plan.AuditComment.ValueString(),
		Description:  plan.Description.ValueString(),
		Locked:       plan.Locked.ValueBool(),
		OperatingsystemIDs: func() []int64 {
			if plan.OperatingsystemIDs.IsNull() || plan.OperatingsystemIDs.IsUnknown() {
				return nil
			}
			var ids []int64
			for _, v := range plan.OperatingsystemIDs.Elements() {
				if iv, ok := v.(types.Int64); ok {
					ids = append(ids, iv.ValueInt64())
				}
			}
			return ids
		}(),
		Snippet: plan.Snippet.ValueBool(),
		TemplateCombinationsAttributes: func() []int64 {
			if plan.TemplateCombinationsAttributes.IsNull() || plan.TemplateCombinationsAttributes.IsUnknown() {
				return nil
			}
			var ids []int64
			for _, v := range plan.TemplateCombinationsAttributes.Elements() {
				if iv, ok := v.(types.Int64); ok {
					ids = append(ids, iv.ValueInt64())
				}
			}
			return ids
		}(),
		TemplateKindID: plan.TemplateKindID.ValueInt64(),
	}
	result, err := r.client.CreateForemanProvisioningTemplate(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create provisioningtemplate, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.Name = types.StringValue(result.Name)
	plan.Template = types.StringValue(result.Template)
	plan.AuditComment = types.StringValue(result.AuditComment)
	plan.Description = types.StringValue(result.Description)
	plan.Locked = types.BoolValue(result.Locked)
	plan.Snippet = types.BoolValue(result.Snippet)
	plan.TemplateKindID = types.Int64Value(int64(result.TemplateKindID))

	tflog.Trace(ctx, "created provisioningtemplate", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *provisioningtemplateResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state provisioningtemplateResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}
	result, err := r.client.ReadForemanProvisioningTemplate(ctx, id)
	if err != nil {
		if generated.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read provisioningtemplate, got error: %s", err))
		return
	}
	state.Name = types.StringValue(result.Name)
	state.Template = types.StringValue(result.Template)
	state.AuditComment = types.StringValue(result.AuditComment)
	state.Description = types.StringValue(result.Description)
	state.Locked = types.BoolValue(result.Locked)
	if result.OperatingsystemIDs != nil {
		elems := make([]attr.Value, len(result.OperatingsystemIDs))
		for i, v := range result.OperatingsystemIDs {
			elems[i] = types.Int64Value(int64(v))
		}
		state.OperatingsystemIDs = types.ListValueMust(types.Int64Type, elems)
	} else {
		state.OperatingsystemIDs = types.ListNull(types.Int64Type)
	}
	state.Snippet = types.BoolValue(result.Snippet)
	if result.TemplateCombinationsAttributes != nil {
		elems := make([]attr.Value, len(result.TemplateCombinationsAttributes))
		for i, v := range result.TemplateCombinationsAttributes {
			elems[i] = types.Int64Value(int64(v))
		}
		state.TemplateCombinationsAttributes = types.ListValueMust(types.Int64Type, elems)
	} else {
		state.TemplateCombinationsAttributes = types.ListNull(types.Int64Type)
	}
	state.TemplateKindID = types.Int64Value(int64(result.TemplateKindID))

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *provisioningtemplateResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan provisioningtemplateResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanProvisioningTemplateRequest{
		Name:         plan.Name.ValueString(),
		Template:     plan.Template.ValueString(),
		AuditComment: plan.AuditComment.ValueString(),
		Description:  plan.Description.ValueString(),
		Locked:       plan.Locked.ValueBool(),
		OperatingsystemIDs: func() []int64 {
			if plan.OperatingsystemIDs.IsNull() || plan.OperatingsystemIDs.IsUnknown() {
				return nil
			}
			var ids []int64
			for _, v := range plan.OperatingsystemIDs.Elements() {
				if iv, ok := v.(types.Int64); ok {
					ids = append(ids, iv.ValueInt64())
				}
			}
			return ids
		}(),
		Snippet: plan.Snippet.ValueBool(),
		TemplateCombinationsAttributes: func() []int64 {
			if plan.TemplateCombinationsAttributes.IsNull() || plan.TemplateCombinationsAttributes.IsUnknown() {
				return nil
			}
			var ids []int64
			for _, v := range plan.TemplateCombinationsAttributes.Elements() {
				if iv, ok := v.(types.Int64); ok {
					ids = append(ids, iv.ValueInt64())
				}
			}
			return ids
		}(),
		TemplateKindID: plan.TemplateKindID.ValueInt64(),
	}
	result, err := r.client.UpdateForemanProvisioningTemplate(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update provisioningtemplate, got error: %s", err))
		return
	}
	plan.Name = types.StringValue(result.Name)
	plan.Template = types.StringValue(result.Template)
	plan.AuditComment = types.StringValue(result.AuditComment)
	plan.Description = types.StringValue(result.Description)
	plan.Locked = types.BoolValue(result.Locked)
	plan.Snippet = types.BoolValue(result.Snippet)
	plan.TemplateKindID = types.Int64Value(int64(result.TemplateKindID))

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *provisioningtemplateResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state provisioningtemplateResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}
	err = r.client.DeleteForemanProvisioningTemplate(ctx, id)
	if err != nil && !generated.IsNotFoundError(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete provisioningtemplate, got error: %s", err))
		return
	}
}

func (r *provisioningtemplateResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
