// Code generated by tools/gen/client/main.go. DO NOT EDIT.
//go:build integration

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccForemanUsergroup_Basic(t *testing.T) {
	resource.ParallelTest(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories(),
		Steps: []resource.TestStep{
			{
				Config: providerConfig + `
resource "foreman_usergroup" "test" {
  name = "test-acc-usergroup"
}
`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet("foreman_usergroup.test", "id"),
					resource.TestCheckResourceAttr("foreman_usergroup.test", "name", "test-acc-usergroup"),
				),
			},
			{
				ResourceName:      "foreman_usergroup.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}
