// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &katelloProductResource{}
	_ resource.ResourceWithImportState = &katelloProductResource{}
)

func NewKatelloProductResource() resource.Resource {
	return &katelloProductResource{}
}

type katelloProductResource struct {
	client *generated.ForemanClient
}

type katelloProductResourceModel struct {
	ID              types.String `tfsdk:"id"`
	Name            types.String `tfsdk:"name"`
	Description     types.String `tfsdk:"description"`
	Label           types.String `tfsdk:"label"`
	GpgKeyID        types.Int64  `tfsdk:"gpg_key_id"`
	SslCaCertID     types.Int64  `tfsdk:"ssl_ca_cert_id"`
	SslClientCertID types.Int64  `tfsdk:"ssl_client_cert_id"`
	SslClientKeyID  types.Int64  `tfsdk:"ssl_client_key_id"`
	SyncPlanID      types.Int64  `tfsdk:"sync_plan_id"`
}

func (r *katelloProductResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_katello_product"
}

func (r *katelloProductResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"description": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"label": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"gpg_key_id": schema.Int64Attribute{
				Required: false,
				Optional: true,
			},
			"ssl_ca_cert_id": schema.Int64Attribute{
				Required: false,
				Optional: true,
			},
			"ssl_client_cert_id": schema.Int64Attribute{
				Required: false,
				Optional: true,
			},
			"ssl_client_key_id": schema.Int64Attribute{
				Required: false,
				Optional: true,
			},
			"sync_plan_id": schema.Int64Attribute{
				Required: false,
				Optional: true,
			},
		},
	}
}

func (r *katelloProductResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}

func (r *katelloProductResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan katelloProductResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanKatelloProductRequest{
		Name:            plan.Name.ValueString(),
		Description:     plan.Description.ValueString(),
		Label:           plan.Label.ValueString(),
		GpgKeyID:        int(plan.GpgKeyID.ValueInt64()),
		SslCaCertID:     int(plan.SslCaCertID.ValueInt64()),
		SslClientCertID: int(plan.SslClientCertID.ValueInt64()),
		SslClientKeyID:  int(plan.SslClientKeyID.ValueInt64()),
		SyncPlanID:      int(plan.SyncPlanID.ValueInt64()),
	}

	result, err := r.client.CreateForemanKatelloProduct(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create katello product, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.Name = types.StringValue(result.Name)
	plan.Description = types.StringValue(result.Description)
	plan.Label = types.StringValue(result.Label)
	plan.GpgKeyID = types.Int64Value(int64(result.GpgKeyID))
	plan.SslCaCertID = types.Int64Value(int64(result.SslCaCertID))
	plan.SslClientCertID = types.Int64Value(int64(result.SslClientCertID))
	plan.SslClientKeyID = types.Int64Value(int64(result.SslClientKeyID))
	plan.SyncPlanID = types.Int64Value(int64(result.SyncPlanID))

	tflog.Trace(ctx, "created katello product", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *katelloProductResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state katelloProductResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanKatelloProduct(ctx, id)
	if err != nil {
		if generated.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read katello product, got error: %s", err))
		return
	}
	state.Name = types.StringValue(result.Name)
	state.Description = types.StringValue(result.Description)
	state.Label = types.StringValue(result.Label)
	state.GpgKeyID = types.Int64Value(int64(result.GpgKeyID))
	state.SslCaCertID = types.Int64Value(int64(result.SslCaCertID))
	state.SslClientCertID = types.Int64Value(int64(result.SslClientCertID))
	state.SslClientKeyID = types.Int64Value(int64(result.SslClientKeyID))
	state.SyncPlanID = types.Int64Value(int64(result.SyncPlanID))

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *katelloProductResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan katelloProductResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanKatelloProductRequest{
		Name:            plan.Name.ValueString(),
		Description:     plan.Description.ValueString(),
		Label:           plan.Label.ValueString(),
		GpgKeyID:        int(plan.GpgKeyID.ValueInt64()),
		SslCaCertID:     int(plan.SslCaCertID.ValueInt64()),
		SslClientCertID: int(plan.SslClientCertID.ValueInt64()),
		SslClientKeyID:  int(plan.SslClientKeyID.ValueInt64()),
		SyncPlanID:      int(plan.SyncPlanID.ValueInt64()),
	}

	result, err := r.client.UpdateForemanKatelloProduct(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update katello product, got error: %s", err))
		return
	}
	plan.Name = types.StringValue(result.Name)
	plan.Description = types.StringValue(result.Description)
	plan.Label = types.StringValue(result.Label)
	plan.GpgKeyID = types.Int64Value(int64(result.GpgKeyID))
	plan.SslCaCertID = types.Int64Value(int64(result.SslCaCertID))
	plan.SslClientCertID = types.Int64Value(int64(result.SslClientCertID))
	plan.SslClientKeyID = types.Int64Value(int64(result.SslClientKeyID))
	plan.SyncPlanID = types.Int64Value(int64(result.SyncPlanID))

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *katelloProductResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state katelloProductResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	err = r.client.DeleteForemanKatelloProduct(ctx, id)
	if err != nil && !generated.IsNotFoundError(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete katello product, got error: %s", err))
		return
	}
}

func (r *katelloProductResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
