// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &operatingsystemResource{}
	_ resource.ResourceWithImportState = &operatingsystemResource{}
)

func NewForemanOperatingSystemResource() resource.Resource {
	return &operatingsystemResource{}
}

type operatingsystemResource struct {
	client *generated.ForemanClient
}

type operatingsystemResourceModel struct {
	ID                      types.String `tfsdk:"id"`
	Major                   types.String `tfsdk:"major"`
	Name                    types.String `tfsdk:"name"`
	ArchitectureIDs         types.List   `tfsdk:"architecture_ids"`
	Description             types.String `tfsdk:"description"`
	Family                  types.String `tfsdk:"family"`
	MediumIDs               types.List   `tfsdk:"medium_ids"`
	Minor                   types.String `tfsdk:"minor"`
	OsParametersAttributes  types.List   `tfsdk:"os_parameters_attributes"`
	PasswordHash            types.String `tfsdk:"password_hash"`
	ProvisioningTemplateIDs types.List   `tfsdk:"provisioning_template_ids"`
	PtableIDs               types.List   `tfsdk:"ptable_ids"`
	ReleaseName             types.String `tfsdk:"release_name"`
}

func (r *operatingsystemResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_operatingsystem"
}

func (r *operatingsystemResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"major": schema.StringAttribute{
				Required: true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"architecture_ids": schema.ListAttribute{
				Required:    false,
				Optional:    true,
				Description: "IDs of associated architectures",
				ElementType: types.Int64Type,
			},
			"description": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"family": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"medium_ids": schema.ListAttribute{
				Required:    false,
				Optional:    true,
				Description: "IDs of associated media",
				ElementType: types.Int64Type,
			},
			"minor": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"os_parameters_attributes": schema.ListAttribute{
				Required:    false,
				Optional:    true,
				Description: "Array of parameters",
				ElementType: types.Int64Type,
			},
			"password_hash": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Root password hash function to use",
			},
			"provisioning_template_ids": schema.ListAttribute{
				Required:    false,
				Optional:    true,
				Description: "IDs of associated provisioning templates",
				ElementType: types.Int64Type,
			},
			"ptable_ids": schema.ListAttribute{
				Required:    false,
				Optional:    true,
				Description: "IDs of associated partition tables",
				ElementType: types.Int64Type,
			},
			"release_name": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
		},
	}
}

func (r *operatingsystemResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}
func (r *operatingsystemResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan operatingsystemResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanOperatingSystemRequest{
		Major:        plan.Major.ValueString(),
		Name:         plan.Name.ValueString(),
		Description:  plan.Description.ValueString(),
		Family:       plan.Family.ValueString(),
		Minor:        plan.Minor.ValueString(),
		PasswordHash: plan.PasswordHash.ValueString(),
		ReleaseName:  plan.ReleaseName.ValueString(),
	}

	result, err := r.client.CreateForemanOperatingSystem(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create operatingsystem, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.Major = types.StringValue(result.Major)
	plan.Name = types.StringValue(result.Name)
	plan.Description = types.StringValue(result.Description)
	plan.Family = types.StringValue(result.Family)
	plan.Minor = types.StringValue(result.Minor)
	plan.PasswordHash = types.StringValue(result.PasswordHash)
	plan.ReleaseName = types.StringValue(result.ReleaseName)

	tflog.Trace(ctx, "created operatingsystem", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *operatingsystemResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state operatingsystemResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanOperatingSystem(ctx, id)
	if err != nil {
		if generated.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read operatingsystem, got error: %s", err))
		return
	}
	state.Major = types.StringValue(result.Major)
	state.Name = types.StringValue(result.Name)
	state.Description = types.StringValue(result.Description)
	state.Family = types.StringValue(result.Family)
	state.Minor = types.StringValue(result.Minor)
	state.PasswordHash = types.StringValue(result.PasswordHash)
	state.ReleaseName = types.StringValue(result.ReleaseName)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *operatingsystemResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan operatingsystemResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanOperatingSystemRequest{
		Major:        plan.Major.ValueString(),
		Name:         plan.Name.ValueString(),
		Description:  plan.Description.ValueString(),
		Family:       plan.Family.ValueString(),
		Minor:        plan.Minor.ValueString(),
		PasswordHash: plan.PasswordHash.ValueString(),
		ReleaseName:  plan.ReleaseName.ValueString(),
	}

	result, err := r.client.UpdateForemanOperatingSystem(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update operatingsystem, got error: %s", err))
		return
	}
	plan.Major = types.StringValue(result.Major)
	plan.Name = types.StringValue(result.Name)
	plan.Description = types.StringValue(result.Description)
	plan.Family = types.StringValue(result.Family)
	plan.Minor = types.StringValue(result.Minor)
	plan.PasswordHash = types.StringValue(result.PasswordHash)
	plan.ReleaseName = types.StringValue(result.ReleaseName)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *operatingsystemResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state operatingsystemResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	err = r.client.DeleteForemanOperatingSystem(ctx, id)
	if err != nil && !generated.IsNotFoundError(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete operatingsystem, got error: %s", err))
		return
	}
}

func (r *operatingsystemResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
