// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &usergroupResource{}
	_ resource.ResourceWithImportState = &usergroupResource{}
)

func NewForemanUsergroupResource() resource.Resource {
	return &usergroupResource{}
}

type usergroupResource struct {
	client *generated.ForemanClient
}

type usergroupResourceModel struct {
	ID           types.String `tfsdk:"id"`
	Name         types.String `tfsdk:"name"`
	Admin        types.Bool   `tfsdk:"admin"`
	RoleIDs      types.List   `tfsdk:"role_ids"`
	UserIDs      types.List   `tfsdk:"user_ids"`
	UsergroupIDs types.List   `tfsdk:"usergroup_ids"`
}

func (r *usergroupResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_usergroup"
}

func (r *usergroupResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"admin": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "is an admin user group, can be modified by admins only",
			},
			"role_ids": schema.ListAttribute{
				Required:    false,
				Optional:    true,
				ElementType: types.Int64Type,
			},
			"user_ids": schema.ListAttribute{
				Required:    false,
				Optional:    true,
				ElementType: types.Int64Type,
			},
			"usergroup_ids": schema.ListAttribute{
				Required:    false,
				Optional:    true,
				ElementType: types.Int64Type,
			},
		},
	}
}

func (r *usergroupResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}
func (r *usergroupResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan usergroupResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanUsergroupRequest{
		Name:  plan.Name.ValueString(),
		Admin: plan.Admin.ValueBool(),
	}

	result, err := r.client.CreateForemanUsergroup(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create usergroup, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.Name = types.StringValue(result.Name)
	plan.Admin = types.BoolValue(result.Admin)

	tflog.Trace(ctx, "created usergroup", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *usergroupResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state usergroupResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanUsergroup(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read usergroup, got error: %s", err))
		return
	}
	state.Name = types.StringValue(result.Name)
	state.Admin = types.BoolValue(result.Admin)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *usergroupResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan usergroupResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanUsergroupRequest{
		Name:  plan.Name.ValueString(),
		Admin: plan.Admin.ValueBool(),
	}

	result, err := r.client.UpdateForemanUsergroup(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update usergroup, got error: %s", err))
		return
	}
	plan.Name = types.StringValue(result.Name)
	plan.Admin = types.BoolValue(result.Admin)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *usergroupResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state usergroupResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	err = r.client.DeleteForemanUsergroup(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete usergroup, got error: %s", err))
		return
	}
}

func (r *usergroupResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
