// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	schema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	planmodifier "github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	stringplanmodifier "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	generated "github.com/terraform-coop/terraform-provider-foreman/generated"
	"strconv"
)

var _ resource.Resource = &jobtemplateResource{}
var _ resource.ResourceWithImportState = &jobtemplateResource{}

func NewForemanJobTemplateResource() resource.Resource {
	return &jobtemplateResource{}
}

type jobtemplateResource struct {
	client *generated.ForemanClient
}

type jobtemplateResourceModel struct {
	ID           types.String `tfsdk:"id"`
	Name         types.String `tfsdk:"name"`
	Description  types.String `tfsdk:"description"`
	JobCategory  types.String `tfsdk:"job_category"`
	ProviderType types.String `tfsdk:"provider_type"`
}

func (r *jobtemplateResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_jobtemplate"
}

func (r *jobtemplateResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{Attributes: map[string]schema.Attribute{
		"description": schema.StringAttribute{
			Optional: true,
			Required: false,
		},
		"id": schema.StringAttribute{
			Computed:      true,
			PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
		},
		"job_category": schema.StringAttribute{
			Optional: true,
			Required: false,
		},
		"name": schema.StringAttribute{
			Optional: true,
			Required: false,
		},
		"provider_type": schema.StringAttribute{
			Optional: true,
			Required: false,
		},
	}}
}

func (r *jobtemplateResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}

func (r *jobtemplateResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan jobtemplateResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanJobTemplateRequest{
		Description:  plan.Description.ValueString(),
		JobCategory:  plan.JobCategory.ValueString(),
		Name:         plan.Name.ValueString(),
		ProviderType: plan.ProviderType.ValueString(),
	}

	result, err := r.client.CreateForemanJobTemplate(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create jobtemplate, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.Name = types.StringValue(result.Name)
	plan.Description = types.StringValue(result.Description)
	plan.JobCategory = types.StringValue(result.JobCategory)
	plan.ProviderType = types.StringValue(result.ProviderType)

	tflog.Trace(ctx, "created jobtemplate", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *jobtemplateResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state jobtemplateResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanJobTemplate(ctx, id)
	if err != nil {
		if generated.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read jobtemplate, got error: %s", err))
		return
	}

	state.Name = types.StringValue(result.Name)
	state.Description = types.StringValue(result.Description)
	state.JobCategory = types.StringValue(result.JobCategory)
	state.ProviderType = types.StringValue(result.ProviderType)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *jobtemplateResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan jobtemplateResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanJobTemplateRequest{
		Description:  plan.Description.ValueString(),
		JobCategory:  plan.JobCategory.ValueString(),
		Name:         plan.Name.ValueString(),
		ProviderType: plan.ProviderType.ValueString(),
	}

	result, err := r.client.UpdateForemanJobTemplate(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update jobtemplate, got error: %s", err))
		return
	}

	plan.Name = types.StringValue(result.Name)
	plan.Description = types.StringValue(result.Description)
	plan.JobCategory = types.StringValue(result.JobCategory)
	plan.ProviderType = types.StringValue(result.ProviderType)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *jobtemplateResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state jobtemplateResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	err = r.client.DeleteForemanJobTemplate(ctx, id)
	if err != nil && !generated.IsNotFoundError(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete jobtemplate, got error: %s", err))
		return
	}
}

func (r *jobtemplateResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
