// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &katelloContentViewResource{}
	_ resource.ResourceWithImportState = &katelloContentViewResource{}
)

func NewKatelloContentViewResource() resource.Resource {
	return &katelloContentViewResource{}
}

type katelloContentViewResource struct {
	client *generated.ForemanClient
}

type katelloContentViewResourceModel struct {
	ID                types.String `tfsdk:"id"`
	Name              types.String `tfsdk:"name"`
	Description       types.String `tfsdk:"description"`
	Label             types.String `tfsdk:"label"`
	OrganizationID    types.Int64  `tfsdk:"organization_id"`
	Composite         types.Bool   `tfsdk:"composite"`
	AutoPublish       types.Bool   `tfsdk:"auto_publish"`
	SolveDependencies types.Bool   `tfsdk:"solve_dependencies"`
	Filtered          types.Bool   `tfsdk:"filtered"`
	LatestVersionID   types.Int64  `tfsdk:"latest_version_id"`
	LatestVersion     types.String `tfsdk:"latest_version"`
	ContentHostCount  types.Int64  `tfsdk:"content_host_count"`
	VersionCount      types.Int64  `tfsdk:"version_count"`
}

func (r *katelloContentViewResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_katello_content_view"
}

func (r *katelloContentViewResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"description": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"label": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"organization_id": schema.Int64Attribute{
				Required: false,
				Optional: true,
			},
			"composite": schema.BoolAttribute{
				Required: false,
				Optional: true,
			},
			"auto_publish": schema.BoolAttribute{
				Required: false,
				Optional: true,
			},
			"solve_dependencies": schema.BoolAttribute{
				Required: false,
				Optional: true,
			},
			"filtered": schema.BoolAttribute{
				Required: false,
				Optional: true,
			},
			"latest_version_id": schema.Int64Attribute{
				Required: false,
				Optional: true,
				Computed: true,
			},
			"latest_version": schema.StringAttribute{
				Required: false,
				Optional: true,
				Computed: true,
			},
			"content_host_count": schema.Int64Attribute{
				Required: false,
				Optional: true,
				Computed: true,
			},
			"version_count": schema.Int64Attribute{
				Required: false,
				Optional: true,
				Computed: true,
			},
		},
	}
}

func (r *katelloContentViewResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}

func (r *katelloContentViewResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan katelloContentViewResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanKatelloContentViewRequest{
		Name:              plan.Name.ValueString(),
		Description:       plan.Description.ValueString(),
		Label:             plan.Label.ValueString(),
		OrganizationID:    int(plan.OrganizationID.ValueInt64()),
		Composite:         plan.Composite.ValueBool(),
		AutoPublish:       plan.AutoPublish.ValueBool(),
		SolveDependencies: plan.SolveDependencies.ValueBool(),
		Filtered:          plan.Filtered.ValueBool(),
	}

	result, err := r.client.CreateForemanKatelloContentView(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create katello content view, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.Name = types.StringValue(result.Name)
	plan.Description = types.StringValue(result.Description)
	plan.Label = types.StringValue(result.Label)
	plan.OrganizationID = types.Int64Value(int64(result.OrganizationID))
	plan.Composite = types.BoolValue(result.Composite)
	plan.AutoPublish = types.BoolValue(result.AutoPublish)
	plan.SolveDependencies = types.BoolValue(result.SolveDependencies)
	plan.Filtered = types.BoolValue(result.Filtered)
	plan.LatestVersionID = types.Int64Value(int64(result.LatestVersionID))
	plan.LatestVersion = types.StringValue(result.LatestVersion)
	plan.ContentHostCount = types.Int64Value(int64(result.ContentHostCount))
	plan.VersionCount = types.Int64Value(int64(result.VersionCount))

	tflog.Trace(ctx, "created katello content view", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *katelloContentViewResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state katelloContentViewResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanKatelloContentView(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read katello content view, got error: %s", err))
		return
	}
	state.Name = types.StringValue(result.Name)
	state.Description = types.StringValue(result.Description)
	state.Label = types.StringValue(result.Label)
	state.OrganizationID = types.Int64Value(int64(result.OrganizationID))
	state.Composite = types.BoolValue(result.Composite)
	state.AutoPublish = types.BoolValue(result.AutoPublish)
	state.SolveDependencies = types.BoolValue(result.SolveDependencies)
	state.Filtered = types.BoolValue(result.Filtered)
	state.LatestVersionID = types.Int64Value(int64(result.LatestVersionID))
	state.LatestVersion = types.StringValue(result.LatestVersion)
	state.ContentHostCount = types.Int64Value(int64(result.ContentHostCount))
	state.VersionCount = types.Int64Value(int64(result.VersionCount))

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *katelloContentViewResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan katelloContentViewResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanKatelloContentViewRequest{
		Name:              plan.Name.ValueString(),
		Description:       plan.Description.ValueString(),
		Label:             plan.Label.ValueString(),
		OrganizationID:    int(plan.OrganizationID.ValueInt64()),
		Composite:         plan.Composite.ValueBool(),
		AutoPublish:       plan.AutoPublish.ValueBool(),
		SolveDependencies: plan.SolveDependencies.ValueBool(),
		Filtered:          plan.Filtered.ValueBool(),
	}

	result, err := r.client.UpdateForemanKatelloContentView(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update katello content view, got error: %s", err))
		return
	}
	plan.Name = types.StringValue(result.Name)
	plan.Description = types.StringValue(result.Description)
	plan.Label = types.StringValue(result.Label)
	plan.OrganizationID = types.Int64Value(int64(result.OrganizationID))
	plan.Composite = types.BoolValue(result.Composite)
	plan.AutoPublish = types.BoolValue(result.AutoPublish)
	plan.SolveDependencies = types.BoolValue(result.SolveDependencies)
	plan.Filtered = types.BoolValue(result.Filtered)
	plan.LatestVersionID = types.Int64Value(int64(result.LatestVersionID))
	plan.LatestVersion = types.StringValue(result.LatestVersion)
	plan.ContentHostCount = types.Int64Value(int64(result.ContentHostCount))
	plan.VersionCount = types.Int64Value(int64(result.VersionCount))

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *katelloContentViewResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state katelloContentViewResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	err = r.client.DeleteForemanKatelloContentView(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete katello content view, got error: %s", err))
		return
	}
}

func (r *katelloContentViewResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
