// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	attr "github.com/hashicorp/terraform-plugin-framework/attr"
	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	schema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	planmodifier "github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	stringplanmodifier "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	generated "github.com/terraform-coop/terraform-provider-foreman/generated"
	"strconv"
)

var _ resource.Resource = &subnetResource{}
var _ resource.ResourceWithImportState = &subnetResource{}

func NewForemanSubnetResource() resource.Resource {
	return &subnetResource{}
}

type subnetResource struct {
	client *generated.ForemanClient
}

type subnetResourceModel struct {
	ID                         types.String `tfsdk:"id"`
	Name                       types.String `tfsdk:"name"`
	Network                    types.String `tfsdk:"network"`
	BmcID                      types.Int64  `tfsdk:"bmc_id"`
	BootMode                   types.String `tfsdk:"boot_mode"`
	Cidr                       types.String `tfsdk:"cidr"`
	Description                types.String `tfsdk:"description"`
	DhcpID                     types.Int64  `tfsdk:"dhcp_id"`
	DNSID                      types.Int64  `tfsdk:"dns_id"`
	DNSPrimary                 types.String `tfsdk:"dns_primary"`
	DNSSecondary               types.String `tfsdk:"dns_secondary"`
	DomainIDs                  types.List   `tfsdk:"domain_ids"`
	ExternalipamGroup          types.String `tfsdk:"externalipam_group"`
	ExternalipamID             types.Int64  `tfsdk:"externalipam_id"`
	From                       types.String `tfsdk:"from"`
	Gateway                    types.String `tfsdk:"gateway"`
	HTTPbootID                 types.Int64  `tfsdk:"httpboot_id"`
	IPam                       types.String `tfsdk:"ipam"`
	Mask                       types.String `tfsdk:"mask"`
	Mtu                        types.Int64  `tfsdk:"mtu"`
	NetworkType                types.String `tfsdk:"network_type"`
	SubnetParametersAttributes types.List   `tfsdk:"subnet_parameters_attributes"`
	TemplateID                 types.Int64  `tfsdk:"template_id"`
	TftpID                     types.Int64  `tfsdk:"tftp_id"`
	To                         types.String `tfsdk:"to"`
	Vlanid                     types.String `tfsdk:"vlanid"`
}

func (r *subnetResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_subnet"
}

func (r *subnetResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{Attributes: map[string]schema.Attribute{
		"bmc_id": schema.Int64Attribute{
			Description: "BMC Proxy ID to use within this subnet",
			Optional:    true,
			Required:    false,
		},
		"boot_mode": schema.StringAttribute{
			Description: "Default boot mode for interfaces assigned to this subnet.",
			Optional:    true,
			Required:    false,
		},
		"cidr": schema.StringAttribute{
			Description: "Network prefix in CIDR notation",
			Optional:    true,
			Required:    false,
		},
		"description": schema.StringAttribute{
			Description: "Subnet description",
			Optional:    true,
			Required:    false,
		},
		"dhcp_id": schema.Int64Attribute{
			Description: "DHCP Proxy ID to use within this subnet",
			Optional:    true,
			Required:    false,
		},
		"dns_id": schema.Int64Attribute{
			Description: "DNS Proxy ID to use within this subnet",
			Optional:    true,
			Required:    false,
		},
		"dns_primary": schema.StringAttribute{
			Description: "Primary DNS for this subnet",
			Optional:    true,
			Required:    false,
		},
		"dns_secondary": schema.StringAttribute{
			Description: "Secondary DNS for this subnet",
			Optional:    true,
			Required:    false,
		},
		"domain_ids": schema.ListAttribute{
			Description: "Domains in which this subnet is part",
			ElementType: types.Int64Type,
			Optional:    true,
			Required:    false,
		},
		"externalipam_group": schema.StringAttribute{
			Description: "External IPAM group - only relevant when IPAM is set to external",
			Optional:    true,
			Required:    false,
		},
		"externalipam_id": schema.Int64Attribute{
			Description: "External IPAM Proxy ID to use within this subnet",
			Optional:    true,
			Required:    false,
		},
		"from": schema.StringAttribute{
			Description: "Starting IP Address for IP auto suggestion",
			Optional:    true,
			Required:    false,
		},
		"gateway": schema.StringAttribute{
			Description: "Subnet gateway",
			Optional:    true,
			Required:    false,
		},
		"httpboot_id": schema.Int64Attribute{
			Description: "HTTPBoot Proxy ID to use within this subnet",
			Optional:    true,
			Required:    false,
		},
		"id": schema.StringAttribute{
			Computed:      true,
			PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
		},
		"ipam": schema.StringAttribute{
			Description: "IP Address auto suggestion mode for this subnet.",
			Optional:    true,
			Required:    false,
		},
		"mask": schema.StringAttribute{
			Description: "Netmask for this subnet",
			Optional:    true,
			Required:    false,
		},
		"mtu": schema.Int64Attribute{
			Description: "MTU for this subnet",
			Optional:    true,
			Required:    false,
		},
		"name": schema.StringAttribute{
			Description: "Subnet name",
			Required:    true,
		},
		"network": schema.StringAttribute{
			Description: "Subnet network",
			Required:    true,
		},
		"network_type": schema.StringAttribute{
			Description: "Type or protocol, IPv4 or IPv6, defaults to IPv4",
			Optional:    true,
			Required:    false,
		},
		"subnet_parameters_attributes": schema.ListAttribute{
			Description: "Array of parameters (name, value)",
			ElementType: types.Int64Type,
			Optional:    true,
			Required:    false,
		},
		"template_id": schema.Int64Attribute{
			Description: "Template HTTP(S) Proxy ID to use within this subnet",
			Optional:    true,
			Required:    false,
		},
		"tftp_id": schema.Int64Attribute{
			Description: "TFTP Proxy ID to use within this subnet",
			Optional:    true,
			Required:    false,
		},
		"to": schema.StringAttribute{
			Description: "Ending IP Address for IP auto suggestion",
			Optional:    true,
			Required:    false,
		},
		"vlanid": schema.StringAttribute{
			Description: "VLAN ID for this subnet",
			Optional:    true,
			Required:    false,
		},
	}}
}

func (r *subnetResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}

func (r *subnetResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan subnetResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanSubnetRequest{
		BmcID:        plan.BmcID.ValueInt64(),
		BootMode:     plan.BootMode.ValueString(),
		Cidr:         plan.Cidr.ValueString(),
		DNSID:        plan.DNSID.ValueInt64(),
		DNSPrimary:   plan.DNSPrimary.ValueString(),
		DNSSecondary: plan.DNSSecondary.ValueString(),
		Description:  plan.Description.ValueString(),
		DhcpID:       plan.DhcpID.ValueInt64(),
		DomainIDs: func() []int64 {
			if plan.DomainIDs.IsNull() || plan.DomainIDs.IsUnknown() {
				return nil
			}
			var ids []int64
			for _, v := range plan.DomainIDs.Elements() {
				if iv, ok := v.(types.Int64); ok {
					ids = append(ids, iv.ValueInt64())
				}
			}
			return ids
		}(),
		ExternalipamGroup: plan.ExternalipamGroup.ValueString(),
		ExternalipamID:    plan.ExternalipamID.ValueInt64(),
		From:              plan.From.ValueString(),
		Gateway:           plan.Gateway.ValueString(),
		HTTPbootID:        plan.HTTPbootID.ValueInt64(),
		IPam:              plan.IPam.ValueString(),
		Mask:              plan.Mask.ValueString(),
		Mtu:               plan.Mtu.ValueInt64(),
		Name:              plan.Name.ValueString(),
		Network:           plan.Network.ValueString(),
		NetworkType:       plan.NetworkType.ValueString(),
		SubnetParametersAttributes: func() []int64 {
			if plan.SubnetParametersAttributes.IsNull() || plan.SubnetParametersAttributes.IsUnknown() {
				return nil
			}
			var ids []int64
			for _, v := range plan.SubnetParametersAttributes.Elements() {
				if iv, ok := v.(types.Int64); ok {
					ids = append(ids, iv.ValueInt64())
				}
			}
			return ids
		}(),
		TemplateID: plan.TemplateID.ValueInt64(),
		TftpID:     plan.TftpID.ValueInt64(),
		To:         plan.To.ValueString(),
		Vlanid:     plan.Vlanid.ValueString(),
	}

	result, err := r.client.CreateForemanSubnet(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create subnet, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.Name = types.StringValue(result.Name)
	plan.Network = types.StringValue(result.Network)
	plan.BmcID = types.Int64Value(int64(result.BmcID))
	plan.BootMode = types.StringValue(result.BootMode)
	plan.Cidr = types.StringValue(result.Cidr)
	plan.Description = types.StringValue(result.Description)
	plan.DhcpID = types.Int64Value(int64(result.DhcpID))
	plan.DNSID = types.Int64Value(int64(result.DNSID))
	plan.DNSPrimary = types.StringValue(result.DNSPrimary)
	plan.DNSSecondary = types.StringValue(result.DNSSecondary)
	plan.ExternalipamGroup = types.StringValue(result.ExternalipamGroup)
	plan.ExternalipamID = types.Int64Value(int64(result.ExternalipamID))
	plan.From = types.StringValue(result.From)
	plan.Gateway = types.StringValue(result.Gateway)
	plan.HTTPbootID = types.Int64Value(int64(result.HTTPbootID))
	plan.IPam = types.StringValue(result.IPam)
	plan.Mask = types.StringValue(result.Mask)
	plan.Mtu = types.Int64Value(int64(result.Mtu))
	plan.NetworkType = types.StringValue(result.NetworkType)
	plan.TemplateID = types.Int64Value(int64(result.TemplateID))
	plan.TftpID = types.Int64Value(int64(result.TftpID))
	plan.To = types.StringValue(result.To)
	plan.Vlanid = types.StringValue(result.Vlanid)

	tflog.Trace(ctx, "created subnet", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *subnetResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state subnetResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanSubnet(ctx, id)
	if err != nil {
		if generated.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read subnet, got error: %s", err))
		return
	}

	state.Name = types.StringValue(result.Name)
	state.Network = types.StringValue(result.Network)
	state.BmcID = types.Int64Value(int64(result.BmcID))
	state.BootMode = types.StringValue(result.BootMode)
	state.Cidr = types.StringValue(result.Cidr)
	state.Description = types.StringValue(result.Description)
	state.DhcpID = types.Int64Value(int64(result.DhcpID))
	state.DNSID = types.Int64Value(int64(result.DNSID))
	state.DNSPrimary = types.StringValue(result.DNSPrimary)
	state.DNSSecondary = types.StringValue(result.DNSSecondary)
	if result.DomainIDs != nil {
		elems := make([]attr.Value, len(result.DomainIDs))
		for i, v := range result.DomainIDs {
			elems[i] = types.Int64Value(int64(v))
		}
		state.DomainIDs = types.ListValueMust(types.Int64Type, elems)
	} else {
		state.DomainIDs = types.ListNull(types.Int64Type)
	}
	state.ExternalipamGroup = types.StringValue(result.ExternalipamGroup)
	state.ExternalipamID = types.Int64Value(int64(result.ExternalipamID))
	state.From = types.StringValue(result.From)
	state.Gateway = types.StringValue(result.Gateway)
	state.HTTPbootID = types.Int64Value(int64(result.HTTPbootID))
	state.IPam = types.StringValue(result.IPam)
	state.Mask = types.StringValue(result.Mask)
	state.Mtu = types.Int64Value(int64(result.Mtu))
	state.NetworkType = types.StringValue(result.NetworkType)
	if result.SubnetParametersAttributes != nil {
		elems := make([]attr.Value, len(result.SubnetParametersAttributes))
		for i, v := range result.SubnetParametersAttributes {
			elems[i] = types.Int64Value(int64(v))
		}
		state.SubnetParametersAttributes = types.ListValueMust(types.Int64Type, elems)
	} else {
		state.SubnetParametersAttributes = types.ListNull(types.Int64Type)
	}
	state.TemplateID = types.Int64Value(int64(result.TemplateID))
	state.TftpID = types.Int64Value(int64(result.TftpID))
	state.To = types.StringValue(result.To)
	state.Vlanid = types.StringValue(result.Vlanid)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *subnetResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan subnetResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanSubnetRequest{
		BmcID:        plan.BmcID.ValueInt64(),
		BootMode:     plan.BootMode.ValueString(),
		Cidr:         plan.Cidr.ValueString(),
		DNSID:        plan.DNSID.ValueInt64(),
		DNSPrimary:   plan.DNSPrimary.ValueString(),
		DNSSecondary: plan.DNSSecondary.ValueString(),
		Description:  plan.Description.ValueString(),
		DhcpID:       plan.DhcpID.ValueInt64(),
		DomainIDs: func() []int64 {
			if plan.DomainIDs.IsNull() || plan.DomainIDs.IsUnknown() {
				return nil
			}
			var ids []int64
			for _, v := range plan.DomainIDs.Elements() {
				if iv, ok := v.(types.Int64); ok {
					ids = append(ids, iv.ValueInt64())
				}
			}
			return ids
		}(),
		ExternalipamGroup: plan.ExternalipamGroup.ValueString(),
		ExternalipamID:    plan.ExternalipamID.ValueInt64(),
		From:              plan.From.ValueString(),
		Gateway:           plan.Gateway.ValueString(),
		HTTPbootID:        plan.HTTPbootID.ValueInt64(),
		IPam:              plan.IPam.ValueString(),
		Mask:              plan.Mask.ValueString(),
		Mtu:               plan.Mtu.ValueInt64(),
		Name:              plan.Name.ValueString(),
		Network:           plan.Network.ValueString(),
		NetworkType:       plan.NetworkType.ValueString(),
		SubnetParametersAttributes: func() []int64 {
			if plan.SubnetParametersAttributes.IsNull() || plan.SubnetParametersAttributes.IsUnknown() {
				return nil
			}
			var ids []int64
			for _, v := range plan.SubnetParametersAttributes.Elements() {
				if iv, ok := v.(types.Int64); ok {
					ids = append(ids, iv.ValueInt64())
				}
			}
			return ids
		}(),
		TemplateID: plan.TemplateID.ValueInt64(),
		TftpID:     plan.TftpID.ValueInt64(),
		To:         plan.To.ValueString(),
		Vlanid:     plan.Vlanid.ValueString(),
	}

	result, err := r.client.UpdateForemanSubnet(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update subnet, got error: %s", err))
		return
	}

	plan.Name = types.StringValue(result.Name)
	plan.Network = types.StringValue(result.Network)
	plan.BmcID = types.Int64Value(int64(result.BmcID))
	plan.BootMode = types.StringValue(result.BootMode)
	plan.Cidr = types.StringValue(result.Cidr)
	plan.Description = types.StringValue(result.Description)
	plan.DhcpID = types.Int64Value(int64(result.DhcpID))
	plan.DNSID = types.Int64Value(int64(result.DNSID))
	plan.DNSPrimary = types.StringValue(result.DNSPrimary)
	plan.DNSSecondary = types.StringValue(result.DNSSecondary)
	plan.ExternalipamGroup = types.StringValue(result.ExternalipamGroup)
	plan.ExternalipamID = types.Int64Value(int64(result.ExternalipamID))
	plan.From = types.StringValue(result.From)
	plan.Gateway = types.StringValue(result.Gateway)
	plan.HTTPbootID = types.Int64Value(int64(result.HTTPbootID))
	plan.IPam = types.StringValue(result.IPam)
	plan.Mask = types.StringValue(result.Mask)
	plan.Mtu = types.Int64Value(int64(result.Mtu))
	plan.NetworkType = types.StringValue(result.NetworkType)
	plan.TemplateID = types.Int64Value(int64(result.TemplateID))
	plan.TftpID = types.Int64Value(int64(result.TftpID))
	plan.To = types.StringValue(result.To)
	plan.Vlanid = types.StringValue(result.Vlanid)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *subnetResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state subnetResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	err = r.client.DeleteForemanSubnet(ctx, id)
	if err != nil && !generated.IsNotFoundError(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete subnet, got error: %s", err))
		return
	}
}

func (r *subnetResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
