// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &computeresourceResource{}
	_ resource.ResourceWithImportState = &computeresourceResource{}
)

func NewForemanComputeResourceResource() resource.Resource {
	return &computeresourceResource{}
}

type computeresourceResource struct {
	client *generated.ForemanClient
}

type computeresourceResourceModel struct {
	ID                 types.String `tfsdk:"id"`
	Name               types.String `tfsdk:"name"`
	CachingEnabled     types.Bool   `tfsdk:"caching_enabled"`
	Datacenter         types.String `tfsdk:"datacenter"`
	Description        types.String `tfsdk:"description"`
	DisplayType        types.String `tfsdk:"display_type"`
	Domain             types.String `tfsdk:"domain"`
	Password           types.String `tfsdk:"password"`
	ProjectDomainID    types.String `tfsdk:"project_domain_id"`
	ProjectDomainName  types.String `tfsdk:"project_domain_name"`
	Provider           types.String `tfsdk:"provider"`
	Region             types.String `tfsdk:"region"`
	Server             types.String `tfsdk:"server"`
	SetConsolePassword types.Bool   `tfsdk:"set_console_password"`
	Tenant             types.String `tfsdk:"tenant"`
	URL                types.String `tfsdk:"url"`
	User               types.String `tfsdk:"user"`
}

func (r *computeresourceResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_computeresource"
}

func (r *computeresourceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"caching_enabled": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "enable caching, for VMware only",
			},
			"datacenter": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "for VMware Datacenter",
			},
			"description": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"display_type": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "for Libvirt only",
			},
			"domain": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "for OpenStack (v3) only",
			},
			"password": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Password for EC2, VMware, OpenStack. Secret key for EC2",
			},
			"project_domain_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "for OpenStack (v3) only",
			},
			"project_domain_name": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "for OpenStack (v3) only",
			},
			"provider": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Providers include Libvirt, EC2, Vmware, Openstack",
			},
			"region": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "for AzureRm eg. &#39;eastus&#39; and for EC2 only. Use &#39;us-gov-west-1&#39; for EC2 GovCloud region",
			},
			"server": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "for VMware",
			},
			"set_console_password": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "for Libvirt and VMware only",
			},
			"tenant": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "for OpenStack and AzureRm only",
			},
			"url": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "URL for Libvirt and OpenStack",
			},
			"user": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Username for EC2, VMware, OpenStack. Access Key for EC2.",
			},
		},
	}
}

func (r *computeresourceResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}
func (r *computeresourceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan computeresourceResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanComputeResourceRequest{
		Name:               plan.Name.ValueString(),
		CachingEnabled:     plan.CachingEnabled.ValueBool(),
		Datacenter:         plan.Datacenter.ValueString(),
		Description:        plan.Description.ValueString(),
		DisplayType:        plan.DisplayType.ValueString(),
		Domain:             plan.Domain.ValueString(),
		Password:           plan.Password.ValueString(),
		ProjectDomainID:    plan.ProjectDomainID.ValueString(),
		ProjectDomainName:  plan.ProjectDomainName.ValueString(),
		Provider:           plan.Provider.ValueString(),
		Region:             plan.Region.ValueString(),
		Server:             plan.Server.ValueString(),
		SetConsolePassword: plan.SetConsolePassword.ValueBool(),
		Tenant:             plan.Tenant.ValueString(),
		URL:                plan.URL.ValueString(),
		User:               plan.User.ValueString(),
	}

	result, err := r.client.CreateForemanComputeResource(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create computeresource, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.Name = types.StringValue(result.Name)
	plan.CachingEnabled = types.BoolValue(result.CachingEnabled)
	plan.Datacenter = types.StringValue(result.Datacenter)
	plan.Description = types.StringValue(result.Description)
	plan.DisplayType = types.StringValue(result.DisplayType)
	plan.Domain = types.StringValue(result.Domain)
	plan.Password = types.StringValue(result.Password)
	plan.ProjectDomainID = types.StringValue(result.ProjectDomainID)
	plan.ProjectDomainName = types.StringValue(result.ProjectDomainName)
	plan.Provider = types.StringValue(result.Provider)
	plan.Region = types.StringValue(result.Region)
	plan.Server = types.StringValue(result.Server)
	plan.SetConsolePassword = types.BoolValue(result.SetConsolePassword)
	plan.Tenant = types.StringValue(result.Tenant)
	plan.URL = types.StringValue(result.URL)
	plan.User = types.StringValue(result.User)

	tflog.Trace(ctx, "created computeresource", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *computeresourceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state computeresourceResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanComputeResource(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read computeresource, got error: %s", err))
		return
	}
	state.Name = types.StringValue(result.Name)
	state.CachingEnabled = types.BoolValue(result.CachingEnabled)
	state.Datacenter = types.StringValue(result.Datacenter)
	state.Description = types.StringValue(result.Description)
	state.DisplayType = types.StringValue(result.DisplayType)
	state.Domain = types.StringValue(result.Domain)
	state.Password = types.StringValue(result.Password)
	state.ProjectDomainID = types.StringValue(result.ProjectDomainID)
	state.ProjectDomainName = types.StringValue(result.ProjectDomainName)
	state.Provider = types.StringValue(result.Provider)
	state.Region = types.StringValue(result.Region)
	state.Server = types.StringValue(result.Server)
	state.SetConsolePassword = types.BoolValue(result.SetConsolePassword)
	state.Tenant = types.StringValue(result.Tenant)
	state.URL = types.StringValue(result.URL)
	state.User = types.StringValue(result.User)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *computeresourceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan computeresourceResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanComputeResourceRequest{
		Name:               plan.Name.ValueString(),
		CachingEnabled:     plan.CachingEnabled.ValueBool(),
		Datacenter:         plan.Datacenter.ValueString(),
		Description:        plan.Description.ValueString(),
		DisplayType:        plan.DisplayType.ValueString(),
		Domain:             plan.Domain.ValueString(),
		Password:           plan.Password.ValueString(),
		ProjectDomainID:    plan.ProjectDomainID.ValueString(),
		ProjectDomainName:  plan.ProjectDomainName.ValueString(),
		Provider:           plan.Provider.ValueString(),
		Region:             plan.Region.ValueString(),
		Server:             plan.Server.ValueString(),
		SetConsolePassword: plan.SetConsolePassword.ValueBool(),
		Tenant:             plan.Tenant.ValueString(),
		URL:                plan.URL.ValueString(),
		User:               plan.User.ValueString(),
	}

	result, err := r.client.UpdateForemanComputeResource(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update computeresource, got error: %s", err))
		return
	}
	plan.Name = types.StringValue(result.Name)
	plan.CachingEnabled = types.BoolValue(result.CachingEnabled)
	plan.Datacenter = types.StringValue(result.Datacenter)
	plan.Description = types.StringValue(result.Description)
	plan.DisplayType = types.StringValue(result.DisplayType)
	plan.Domain = types.StringValue(result.Domain)
	plan.Password = types.StringValue(result.Password)
	plan.ProjectDomainID = types.StringValue(result.ProjectDomainID)
	plan.ProjectDomainName = types.StringValue(result.ProjectDomainName)
	plan.Provider = types.StringValue(result.Provider)
	plan.Region = types.StringValue(result.Region)
	plan.Server = types.StringValue(result.Server)
	plan.SetConsolePassword = types.BoolValue(result.SetConsolePassword)
	plan.Tenant = types.StringValue(result.Tenant)
	plan.URL = types.StringValue(result.URL)
	plan.User = types.StringValue(result.User)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *computeresourceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state computeresourceResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	err = r.client.DeleteForemanComputeResource(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete computeresource, got error: %s", err))
		return
	}
}

func (r *computeresourceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
