// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &mediumResource{}
	_ resource.ResourceWithImportState = &mediumResource{}
)

func NewForemanMediumResource() resource.Resource {
	return &mediumResource{}
}

type mediumResource struct {
	client *generated.ForemanClient
}

type mediumResourceModel struct {
	ID                 types.String `tfsdk:"id"`
	Name               types.String `tfsdk:"name"`
	Path               types.String `tfsdk:"path"`
	OperatingsystemIDs types.List   `tfsdk:"operatingsystem_ids"`
	OsFamily           types.String `tfsdk:"os_family"`
}

func (r *mediumResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_medium"
}

func (r *mediumResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "Name of media",
			},
			"path": schema.StringAttribute{
				Required:    true,
				Description: "The path to the medium, can be a URL or a valid NFS server (exclusive of the architecture).  for example mirror.centos.org/centos/$version/os/$arch where $arch will be substituted for the host&#39;s actual OS architecture and $version, $major and $minor will be substituted for the version of the operating system.  Solaris and Debian media may also use $release.",
			},
			"operatingsystem_ids": schema.ListAttribute{
				Required:    false,
				Optional:    true,
				ElementType: types.Int64Type,
			},
			"os_family": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Operating system family, available values: AIX, Altlinux, Archlinux, Coreos, Debian, Fcos, Freebsd, Gentoo, Junos, NXOS, Rancheros, Redhat, Rhcos, Solaris, Suse, VRP, Windows, Xenserver",
			},
		},
	}
}

func (r *mediumResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}
func (r *mediumResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan mediumResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanMediumRequest{
		Name:     plan.Name.ValueString(),
		Path:     plan.Path.ValueString(),
		OsFamily: plan.OsFamily.ValueString(),
	}

	result, err := r.client.CreateForemanMedium(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create medium, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.Name = types.StringValue(result.Name)
	plan.Path = types.StringValue(result.Path)
	plan.OsFamily = types.StringValue(result.OsFamily)

	tflog.Trace(ctx, "created medium", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mediumResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state mediumResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanMedium(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read medium, got error: %s", err))
		return
	}
	state.Name = types.StringValue(result.Name)
	state.Path = types.StringValue(result.Path)
	state.OsFamily = types.StringValue(result.OsFamily)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *mediumResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan mediumResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanMediumRequest{
		Name:     plan.Name.ValueString(),
		Path:     plan.Path.ValueString(),
		OsFamily: plan.OsFamily.ValueString(),
	}

	result, err := r.client.UpdateForemanMedium(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update medium, got error: %s", err))
		return
	}
	plan.Name = types.StringValue(result.Name)
	plan.Path = types.StringValue(result.Path)
	plan.OsFamily = types.StringValue(result.OsFamily)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *mediumResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state mediumResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	err = r.client.DeleteForemanMedium(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete medium, got error: %s", err))
		return
	}
}

func (r *mediumResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
