// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &parameterResource{}
	_ resource.ResourceWithImportState = &parameterResource{}
)

func NewForemanParameterResource() resource.Resource {
	return &parameterResource{}
}

type parameterResource struct {
	client *generated.ForemanClient
}

type parameterResourceModel struct {
	ID            types.String `tfsdk:"id"`
	Name          types.String `tfsdk:"name"`
	ParameterType types.String `tfsdk:"parameter_type"`
	Value         types.String `tfsdk:"value"`
	HiddenValue   types.Bool   `tfsdk:"hidden_value"`
}

func (r *parameterResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_parameter"
}

func (r *parameterResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"parameter_type": schema.StringAttribute{
				Required:    true,
				Description: "Type of value",
			},
			"value": schema.StringAttribute{
				Required: true,
			},
			"hidden_value": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Should the value be hidden",
			},
		},
	}
}

func (r *parameterResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}
func (r *parameterResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan parameterResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanParameterRequest{
		Name:          plan.Name.ValueString(),
		ParameterType: plan.ParameterType.ValueString(),
		Value:         plan.Value.ValueString(),
		HiddenValue:   plan.HiddenValue.ValueBool(),
	}

	result, err := r.client.CreateForemanParameter(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create parameter, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.Name = types.StringValue(result.Name)
	plan.ParameterType = types.StringValue(result.ParameterType)
	plan.Value = types.StringValue(result.Value)
	plan.HiddenValue = types.BoolValue(result.HiddenValue)

	tflog.Trace(ctx, "created parameter", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *parameterResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state parameterResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanParameter(ctx, id)
	if err != nil {
		if generated.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read parameter, got error: %s", err))
		return
	}
	state.Name = types.StringValue(result.Name)
	state.ParameterType = types.StringValue(result.ParameterType)
	state.Value = types.StringValue(result.Value)
	state.HiddenValue = types.BoolValue(result.HiddenValue)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *parameterResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan parameterResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanParameterRequest{
		Name:          plan.Name.ValueString(),
		ParameterType: plan.ParameterType.ValueString(),
		Value:         plan.Value.ValueString(),
		HiddenValue:   plan.HiddenValue.ValueBool(),
	}

	result, err := r.client.UpdateForemanParameter(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update parameter, got error: %s", err))
		return
	}
	plan.Name = types.StringValue(result.Name)
	plan.ParameterType = types.StringValue(result.ParameterType)
	plan.Value = types.StringValue(result.Value)
	plan.HiddenValue = types.BoolValue(result.HiddenValue)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *parameterResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state parameterResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	err = r.client.DeleteForemanParameter(ctx, id)
	if err != nil && !generated.IsNotFoundError(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete parameter, got error: %s", err))
		return
	}
}

func (r *parameterResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
