// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-coop/terraform-provider-foreman/generated"
)

var (
	_ resource.Resource                = &override_valueResource{}
	_ resource.ResourceWithImportState = &override_valueResource{}
)

func NewForemanOverrideValueResource() resource.Resource {
	return &override_valueResource{}
}

type override_valueResource struct {
	client *generated.ForemanClient
}

type override_valueResourceModel struct {
	ID       types.String `tfsdk:"id"`
	ParentID types.Int64  `tfsdk:"parent_id"`
	Match    types.String `tfsdk:"match"`
	Value    types.String `tfsdk:"value"`
	Omit     types.Bool   `tfsdk:"omit"`
}

func (r *override_valueResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_override_value"
}

func (r *override_valueResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"parent_id": schema.Int64Attribute{
				Required:    true,
				Description: "ID of the parent resource.",
			},
			"match": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"value": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"omit": schema.BoolAttribute{
				Required: false,
				Optional: true,
			},
		},
	}
}

func (r *override_valueResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}
func (r *override_valueResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan override_valueResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanOverrideValueRequest{
		Match: plan.Match.ValueString(),
		Value: plan.Value.ValueString(),
		Omit:  plan.Omit.ValueBool(),
	}
	parentID := int(plan.ParentID.ValueInt64())
	result, err := r.client.CreateForemanOverrideValue(ctx, parentID, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create override_value, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.Match = types.StringValue(result.Match)
	plan.Value = types.StringValue(result.Value)
	plan.Omit = types.BoolValue(result.Omit)

	tflog.Trace(ctx, "created override_value", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *override_valueResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state override_valueResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}
	parentID := int(state.ParentID.ValueInt64())
	result, err := r.client.ReadForemanOverrideValue(ctx, parentID, id)
	if err != nil {
		if generated.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read override_value, got error: %s", err))
		return
	}
	state.Match = types.StringValue(result.Match)
	state.Value = types.StringValue(result.Value)
	state.Omit = types.BoolValue(result.Omit)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *override_valueResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan override_valueResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanOverrideValueRequest{
		Match: plan.Match.ValueString(),
		Value: plan.Value.ValueString(),
		Omit:  plan.Omit.ValueBool(),
	}
	parentID := int(plan.ParentID.ValueInt64())
	result, err := r.client.UpdateForemanOverrideValue(ctx, parentID, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update override_value, got error: %s", err))
		return
	}
	plan.Match = types.StringValue(result.Match)
	plan.Value = types.StringValue(result.Value)
	plan.Omit = types.BoolValue(result.Omit)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *override_valueResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state override_valueResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}
	parentID := int(state.ParentID.ValueInt64())
	err = r.client.DeleteForemanOverrideValue(ctx, parentID, id)
	if err != nil && !generated.IsNotFoundError(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete override_value, got error: %s", err))
		return
	}
}

func (r *override_valueResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
