// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	attr "github.com/hashicorp/terraform-plugin-framework/attr"
	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	schema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	planmodifier "github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	stringplanmodifier "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	generated "github.com/terraform-coop/terraform-provider-foreman/generated"
	"strconv"
)

var _ resource.Resource = &userResource{}
var _ resource.ResourceWithImportState = &userResource{}

func NewForemanUserResource() resource.Resource {
	return &userResource{}
}

type userResource struct {
	client *generated.ForemanClient
}

type userResourceModel struct {
	ID                    types.String `tfsdk:"id"`
	AuthSourceID          types.Int64  `tfsdk:"auth_source_id"`
	Login                 types.String `tfsdk:"login"`
	Mail                  types.String `tfsdk:"mail"`
	Admin                 types.Bool   `tfsdk:"admin"`
	DefaultLocationID     types.Int64  `tfsdk:"default_location_id"`
	DefaultOrganizationID types.Int64  `tfsdk:"default_organization_id"`
	Description           types.String `tfsdk:"description"`
	Disabled              types.Bool   `tfsdk:"disabled"`
	Firstname             types.String `tfsdk:"firstname"`
	Lastname              types.String `tfsdk:"lastname"`
	Locale                types.String `tfsdk:"locale"`
	MailEnabled           types.Bool   `tfsdk:"mail_enabled"`
	Password              types.String `tfsdk:"password"`
	RoleIDs               types.List   `tfsdk:"role_ids"`
	Timezone              types.String `tfsdk:"timezone"`
	UiCompactMode         types.Bool   `tfsdk:"ui_compact_mode"`
}

func (r *userResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_user"
}

func (r *userResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{Attributes: map[string]schema.Attribute{
		"admin": schema.BoolAttribute{
			Description: "is an admin account",
			Optional:    true,
			Required:    false,
		},
		"auth_source_id": schema.Int64Attribute{Required: true},
		"default_location_id": schema.Int64Attribute{
			Optional: true,
			Required: false,
		},
		"default_organization_id": schema.Int64Attribute{
			Optional: true,
			Required: false,
		},
		"description": schema.StringAttribute{
			Optional: true,
			Required: false,
		},
		"disabled": schema.BoolAttribute{
			Optional: true,
			Required: false,
		},
		"firstname": schema.StringAttribute{
			Optional: true,
			Required: false,
		},
		"id": schema.StringAttribute{
			Computed:      true,
			PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
		},
		"lastname": schema.StringAttribute{
			Optional: true,
			Required: false,
		},
		"locale": schema.StringAttribute{
			Description: "User&#39;s preferred locale",
			Optional:    true,
			Required:    false,
		},
		"login": schema.StringAttribute{Required: true},
		"mail":  schema.StringAttribute{Required: true},
		"mail_enabled": schema.BoolAttribute{
			Description: "Enable user&#39;s email",
			Optional:    true,
			Required:    false,
		},
		"password": schema.StringAttribute{
			Description: "Required unless user is in an external authentication source",
			Optional:    true,
			Required:    false,
		},
		"role_ids": schema.ListAttribute{
			ElementType: types.Int64Type,
			Optional:    true,
			Required:    false,
		},
		"timezone": schema.StringAttribute{
			Description: "User&#39;s timezone",
			Optional:    true,
			Required:    false,
		},
		"ui_compact_mode": schema.BoolAttribute{
			Description: "Use compact UI",
			Optional:    true,
			Required:    false,
		},
	}}
}

func (r *userResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}

func (r *userResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan userResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanUserRequest{
		Admin:                 plan.Admin.ValueBool(),
		AuthSourceID:          plan.AuthSourceID.ValueInt64(),
		DefaultLocationID:     plan.DefaultLocationID.ValueInt64(),
		DefaultOrganizationID: plan.DefaultOrganizationID.ValueInt64(),
		Description:           plan.Description.ValueString(),
		Disabled:              plan.Disabled.ValueBool(),
		Firstname:             plan.Firstname.ValueString(),
		Lastname:              plan.Lastname.ValueString(),
		Locale:                plan.Locale.ValueString(),
		Login:                 plan.Login.ValueString(),
		Mail:                  plan.Mail.ValueString(),
		MailEnabled:           plan.MailEnabled.ValueBool(),
		Password:              plan.Password.ValueString(),
		RoleIDs: func() []int64 {
			if plan.RoleIDs.IsNull() || plan.RoleIDs.IsUnknown() {
				return nil
			}
			var ids []int64
			for _, v := range plan.RoleIDs.Elements() {
				if iv, ok := v.(types.Int64); ok {
					ids = append(ids, iv.ValueInt64())
				}
			}
			return ids
		}(),
		Timezone:      plan.Timezone.ValueString(),
		UiCompactMode: plan.UiCompactMode.ValueBool(),
	}

	result, err := r.client.CreateForemanUser(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create user, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.AuthSourceID = types.Int64Value(int64(result.AuthSourceID))
	plan.Login = types.StringValue(result.Login)
	plan.Mail = types.StringValue(result.Mail)
	plan.Admin = types.BoolValue(result.Admin)
	plan.DefaultLocationID = types.Int64Value(int64(result.DefaultLocationID))
	plan.DefaultOrganizationID = types.Int64Value(int64(result.DefaultOrganizationID))
	plan.Description = types.StringValue(result.Description)
	plan.Disabled = types.BoolValue(result.Disabled)
	plan.Firstname = types.StringValue(result.Firstname)
	plan.Lastname = types.StringValue(result.Lastname)
	plan.Locale = types.StringValue(result.Locale)
	plan.MailEnabled = types.BoolValue(result.MailEnabled)
	plan.Password = types.StringValue(result.Password)
	plan.Timezone = types.StringValue(result.Timezone)
	plan.UiCompactMode = types.BoolValue(result.UiCompactMode)

	tflog.Trace(ctx, "created user", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *userResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state userResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanUser(ctx, id)
	if err != nil {
		if generated.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read user, got error: %s", err))
		return
	}

	state.AuthSourceID = types.Int64Value(int64(result.AuthSourceID))
	state.Login = types.StringValue(result.Login)
	state.Mail = types.StringValue(result.Mail)
	state.Admin = types.BoolValue(result.Admin)
	state.DefaultLocationID = types.Int64Value(int64(result.DefaultLocationID))
	state.DefaultOrganizationID = types.Int64Value(int64(result.DefaultOrganizationID))
	state.Description = types.StringValue(result.Description)
	state.Disabled = types.BoolValue(result.Disabled)
	state.Firstname = types.StringValue(result.Firstname)
	state.Lastname = types.StringValue(result.Lastname)
	state.Locale = types.StringValue(result.Locale)
	state.MailEnabled = types.BoolValue(result.MailEnabled)
	state.Password = types.StringValue(result.Password)
	if result.RoleIDs != nil {
		elems := make([]attr.Value, len(result.RoleIDs))
		for i, v := range result.RoleIDs {
			elems[i] = types.Int64Value(int64(v))
		}
		state.RoleIDs = types.ListValueMust(types.Int64Type, elems)
	} else {
		state.RoleIDs = types.ListNull(types.Int64Type)
	}
	state.Timezone = types.StringValue(result.Timezone)
	state.UiCompactMode = types.BoolValue(result.UiCompactMode)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *userResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan userResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanUserRequest{
		Admin:                 plan.Admin.ValueBool(),
		AuthSourceID:          plan.AuthSourceID.ValueInt64(),
		DefaultLocationID:     plan.DefaultLocationID.ValueInt64(),
		DefaultOrganizationID: plan.DefaultOrganizationID.ValueInt64(),
		Description:           plan.Description.ValueString(),
		Disabled:              plan.Disabled.ValueBool(),
		Firstname:             plan.Firstname.ValueString(),
		Lastname:              plan.Lastname.ValueString(),
		Locale:                plan.Locale.ValueString(),
		Login:                 plan.Login.ValueString(),
		Mail:                  plan.Mail.ValueString(),
		MailEnabled:           plan.MailEnabled.ValueBool(),
		Password:              plan.Password.ValueString(),
		RoleIDs: func() []int64 {
			if plan.RoleIDs.IsNull() || plan.RoleIDs.IsUnknown() {
				return nil
			}
			var ids []int64
			for _, v := range plan.RoleIDs.Elements() {
				if iv, ok := v.(types.Int64); ok {
					ids = append(ids, iv.ValueInt64())
				}
			}
			return ids
		}(),
		Timezone:      plan.Timezone.ValueString(),
		UiCompactMode: plan.UiCompactMode.ValueBool(),
	}

	result, err := r.client.UpdateForemanUser(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update user, got error: %s", err))
		return
	}

	plan.AuthSourceID = types.Int64Value(int64(result.AuthSourceID))
	plan.Login = types.StringValue(result.Login)
	plan.Mail = types.StringValue(result.Mail)
	plan.Admin = types.BoolValue(result.Admin)
	plan.DefaultLocationID = types.Int64Value(int64(result.DefaultLocationID))
	plan.DefaultOrganizationID = types.Int64Value(int64(result.DefaultOrganizationID))
	plan.Description = types.StringValue(result.Description)
	plan.Disabled = types.BoolValue(result.Disabled)
	plan.Firstname = types.StringValue(result.Firstname)
	plan.Lastname = types.StringValue(result.Lastname)
	plan.Locale = types.StringValue(result.Locale)
	plan.MailEnabled = types.BoolValue(result.MailEnabled)
	plan.Password = types.StringValue(result.Password)
	plan.Timezone = types.StringValue(result.Timezone)
	plan.UiCompactMode = types.BoolValue(result.UiCompactMode)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *userResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state userResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	err = r.client.DeleteForemanUser(ctx, id)
	if err != nil && !generated.IsNotFoundError(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete user, got error: %s", err))
		return
	}
}

func (r *userResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
