// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-coop/terraform-provider-foreman/generated"
)

var (
	_ resource.Resource                = &webhook_templateResource{}
	_ resource.ResourceWithImportState = &webhook_templateResource{}
)

func NewForemanWebhookTemplateResource() resource.Resource {
	return &webhook_templateResource{}
}

type webhook_templateResource struct {
	client *generated.ForemanClient
}

type webhook_templateResourceModel struct {
	ID           types.String `tfsdk:"id"`
	Name         types.String `tfsdk:"name"`
	Template     types.String `tfsdk:"template"`
	Snippet      types.Bool   `tfsdk:"snippet"`
	AuditComment types.String `tfsdk:"audit_comment"`
	Locked       types.Bool   `tfsdk:"locked"`
	Default      types.Bool   `tfsdk:"default"`
	Description  types.String `tfsdk:"description"`
}

func (r *webhook_templateResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_webhook_template"
}

func (r *webhook_templateResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"template": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"snippet": schema.BoolAttribute{
				Required: false,
				Optional: true,
			},
			"audit_comment": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"locked": schema.BoolAttribute{
				Required: false,
				Optional: true,
			},
			"default": schema.BoolAttribute{
				Required: false,
				Optional: true,
			},
			"description": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
		},
	}
}

func (r *webhook_templateResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}
func (r *webhook_templateResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan webhook_templateResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanWebhookTemplateRequest{
		Name:         plan.Name.ValueString(),
		Template:     plan.Template.ValueString(),
		Snippet:      plan.Snippet.ValueBool(),
		AuditComment: plan.AuditComment.ValueString(),
		Locked:       plan.Locked.ValueBool(),
		Default:      plan.Default.ValueBool(),
		Description:  plan.Description.ValueString(),
	}

	result, err := r.client.CreateForemanWebhookTemplate(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create webhook_template, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.Name = types.StringValue(result.Name)
	plan.Template = types.StringValue(result.Template)
	plan.Snippet = types.BoolValue(result.Snippet)
	plan.AuditComment = types.StringValue(result.AuditComment)
	plan.Locked = types.BoolValue(result.Locked)
	plan.Default = types.BoolValue(result.Default)
	plan.Description = types.StringValue(result.Description)

	tflog.Trace(ctx, "created webhook_template", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *webhook_templateResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state webhook_templateResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanWebhookTemplate(ctx, id)
	if err != nil {
		if generated.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read webhook_template, got error: %s", err))
		return
	}
	state.Name = types.StringValue(result.Name)
	state.Template = types.StringValue(result.Template)
	state.Snippet = types.BoolValue(result.Snippet)
	state.AuditComment = types.StringValue(result.AuditComment)
	state.Locked = types.BoolValue(result.Locked)
	state.Default = types.BoolValue(result.Default)
	state.Description = types.StringValue(result.Description)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *webhook_templateResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan webhook_templateResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanWebhookTemplateRequest{
		Name:         plan.Name.ValueString(),
		Template:     plan.Template.ValueString(),
		Snippet:      plan.Snippet.ValueBool(),
		AuditComment: plan.AuditComment.ValueString(),
		Locked:       plan.Locked.ValueBool(),
		Default:      plan.Default.ValueBool(),
		Description:  plan.Description.ValueString(),
	}

	result, err := r.client.UpdateForemanWebhookTemplate(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update webhook_template, got error: %s", err))
		return
	}
	plan.Name = types.StringValue(result.Name)
	plan.Template = types.StringValue(result.Template)
	plan.Snippet = types.BoolValue(result.Snippet)
	plan.AuditComment = types.StringValue(result.AuditComment)
	plan.Locked = types.BoolValue(result.Locked)
	plan.Default = types.BoolValue(result.Default)
	plan.Description = types.StringValue(result.Description)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *webhook_templateResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state webhook_templateResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	err = r.client.DeleteForemanWebhookTemplate(ctx, id)
	if err != nil && !generated.IsNotFoundError(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete webhook_template, got error: %s", err))
		return
	}
}

func (r *webhook_templateResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
