// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-coop/terraform-provider-foreman/generated"
)

var (
	_ resource.Resource                = &imageResource{}
	_ resource.ResourceWithImportState = &imageResource{}
)

func NewForemanImageResource() resource.Resource {
	return &imageResource{}
}

type imageResource struct {
	client *generated.ForemanClient
}

type imageResourceModel struct {
	ID                types.String `tfsdk:"id"`
	Name              types.String `tfsdk:"name"`
	Username          types.String `tfsdk:"username"`
	UUID              types.String `tfsdk:"uuid"`
	ArchitectureID    types.String `tfsdk:"architecture_id"`
	ComputeResourceID types.String `tfsdk:"compute_resource_id"`
	OperatingsystemID types.Int64  `tfsdk:"operatingsystem_id"`
	Password          types.String `tfsdk:"password"`
	UserData          types.Bool   `tfsdk:"user_data"`
}

func (r *imageResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_image"
}

func (r *imageResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"username": schema.StringAttribute{
				Required: true,
			},
			"uuid": schema.StringAttribute{
				Required:    true,
				Description: "Template ID in the compute resource",
			},
			"architecture_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "ID of architecture",
			},
			"compute_resource_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "ID of compute resource",
			},
			"operatingsystem_id": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Description: "ID of operating system",
			},
			"password": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"user_data": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Whether or not the image supports user data",
			},
		},
	}
}

func (r *imageResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}
func (r *imageResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan imageResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanImageRequest{
		Name:              plan.Name.ValueString(),
		Username:          plan.Username.ValueString(),
		UUID:              plan.UUID.ValueString(),
		ArchitectureID:    plan.ArchitectureID.ValueString(),
		ComputeResourceID: plan.ComputeResourceID.ValueString(),
		OperatingsystemID: plan.OperatingsystemID.ValueInt64(),
		Password:          plan.Password.ValueString(),
		UserData:          plan.UserData.ValueBool(),
	}
	result, err := r.client.CreateForemanImage(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create image, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.Name = types.StringValue(result.Name)
	plan.Username = types.StringValue(result.Username)
	plan.UUID = types.StringValue(result.UUID)
	plan.ArchitectureID = types.StringValue(result.ArchitectureID)
	plan.ComputeResourceID = types.StringValue(result.ComputeResourceID)
	plan.OperatingsystemID = types.Int64Value(int64(result.OperatingsystemID))
	plan.Password = types.StringValue(result.Password)
	plan.UserData = types.BoolValue(result.UserData)

	tflog.Trace(ctx, "created image", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *imageResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state imageResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}
	result, err := r.client.ReadForemanImage(ctx, id)
	if err != nil {
		if generated.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read image, got error: %s", err))
		return
	}
	state.Name = types.StringValue(result.Name)
	state.Username = types.StringValue(result.Username)
	state.UUID = types.StringValue(result.UUID)
	state.ArchitectureID = types.StringValue(result.ArchitectureID)
	state.ComputeResourceID = types.StringValue(result.ComputeResourceID)
	state.OperatingsystemID = types.Int64Value(int64(result.OperatingsystemID))
	state.Password = types.StringValue(result.Password)
	state.UserData = types.BoolValue(result.UserData)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *imageResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan imageResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanImageRequest{
		Name:              plan.Name.ValueString(),
		Username:          plan.Username.ValueString(),
		UUID:              plan.UUID.ValueString(),
		ArchitectureID:    plan.ArchitectureID.ValueString(),
		ComputeResourceID: plan.ComputeResourceID.ValueString(),
		OperatingsystemID: plan.OperatingsystemID.ValueInt64(),
		Password:          plan.Password.ValueString(),
		UserData:          plan.UserData.ValueBool(),
	}
	result, err := r.client.UpdateForemanImage(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update image, got error: %s", err))
		return
	}
	plan.Name = types.StringValue(result.Name)
	plan.Username = types.StringValue(result.Username)
	plan.UUID = types.StringValue(result.UUID)
	plan.ArchitectureID = types.StringValue(result.ArchitectureID)
	plan.ComputeResourceID = types.StringValue(result.ComputeResourceID)
	plan.OperatingsystemID = types.Int64Value(int64(result.OperatingsystemID))
	plan.Password = types.StringValue(result.Password)
	plan.UserData = types.BoolValue(result.UserData)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *imageResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state imageResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}
	err = r.client.DeleteForemanImage(ctx, id)
	if err != nil && !generated.IsNotFoundError(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete image, got error: %s", err))
		return
	}
}

func (r *imageResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
