// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	schema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	planmodifier "github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	stringplanmodifier "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	generated "github.com/terraform-coop/terraform-provider-foreman/generated"
	"strconv"
)

var _ resource.Resource = &discovery_ruleResource{}
var _ resource.ResourceWithImportState = &discovery_ruleResource{}

func NewForemanDiscoveryRuleResource() resource.Resource {
	return &discovery_ruleResource{}
}

type discovery_ruleResource struct {
	client *generated.ForemanClient
}

type discovery_ruleResourceModel struct {
	ID                 types.String `tfsdk:"id"`
	Name               types.String `tfsdk:"name"`
	Search             types.String `tfsdk:"search"`
	HostgroupID        types.Int64  `tfsdk:"hostgroup_id"`
	Hostname           types.String `tfsdk:"hostname"`
	HostsLimitMaxCount types.Int64  `tfsdk:"hosts_limit"`
	Priority           types.Int64  `tfsdk:"priority"`
	Enabled            types.Bool   `tfsdk:"enabled"`
}

func (r *discovery_ruleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_discovery_rule"
}

func (r *discovery_ruleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{Attributes: map[string]schema.Attribute{
		"enabled": schema.BoolAttribute{
			Optional: true,
			Required: false,
		},
		"hostgroup_id": schema.Int64Attribute{
			Optional: true,
			Required: false,
		},
		"hostname": schema.StringAttribute{
			Optional: true,
			Required: false,
		},
		"hosts_limit": schema.Int64Attribute{
			Optional: true,
			Required: false,
		},
		"id": schema.StringAttribute{
			Computed:      true,
			PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
		},
		"name": schema.StringAttribute{
			Optional: true,
			Required: false,
		},
		"priority": schema.Int64Attribute{
			Optional: true,
			Required: false,
		},
		"search": schema.StringAttribute{
			Optional: true,
			Required: false,
		},
	}}
}

func (r *discovery_ruleResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}

func (r *discovery_ruleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan discovery_ruleResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanDiscoveryRuleRequest{
		Enabled:            plan.Enabled.ValueBool(),
		HostgroupID:        plan.HostgroupID.ValueInt64(),
		Hostname:           plan.Hostname.ValueString(),
		HostsLimitMaxCount: plan.HostsLimitMaxCount.ValueInt64(),
		Name:               plan.Name.ValueString(),
		Priority:           plan.Priority.ValueInt64(),
		Search:             plan.Search.ValueString(),
	}

	result, err := r.client.CreateForemanDiscoveryRule(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create discovery_rule, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.Name = types.StringValue(result.Name)
	plan.Search = types.StringValue(result.Search)
	plan.HostgroupID = types.Int64Value(int64(result.HostgroupID))
	plan.Hostname = types.StringValue(result.Hostname)
	plan.HostsLimitMaxCount = types.Int64Value(int64(result.HostsLimitMaxCount))
	plan.Priority = types.Int64Value(int64(result.Priority))
	plan.Enabled = types.BoolValue(result.Enabled)

	tflog.Trace(ctx, "created discovery_rule", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *discovery_ruleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state discovery_ruleResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanDiscoveryRule(ctx, id)
	if err != nil {
		if generated.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read discovery_rule, got error: %s", err))
		return
	}

	state.Name = types.StringValue(result.Name)
	state.Search = types.StringValue(result.Search)
	state.HostgroupID = types.Int64Value(int64(result.HostgroupID))
	state.Hostname = types.StringValue(result.Hostname)
	state.HostsLimitMaxCount = types.Int64Value(int64(result.HostsLimitMaxCount))
	state.Priority = types.Int64Value(int64(result.Priority))
	state.Enabled = types.BoolValue(result.Enabled)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *discovery_ruleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan discovery_ruleResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanDiscoveryRuleRequest{
		Enabled:            plan.Enabled.ValueBool(),
		HostgroupID:        plan.HostgroupID.ValueInt64(),
		Hostname:           plan.Hostname.ValueString(),
		HostsLimitMaxCount: plan.HostsLimitMaxCount.ValueInt64(),
		Name:               plan.Name.ValueString(),
		Priority:           plan.Priority.ValueInt64(),
		Search:             plan.Search.ValueString(),
	}

	result, err := r.client.UpdateForemanDiscoveryRule(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update discovery_rule, got error: %s", err))
		return
	}

	plan.Name = types.StringValue(result.Name)
	plan.Search = types.StringValue(result.Search)
	plan.HostgroupID = types.Int64Value(int64(result.HostgroupID))
	plan.Hostname = types.StringValue(result.Hostname)
	plan.HostsLimitMaxCount = types.Int64Value(int64(result.HostsLimitMaxCount))
	plan.Priority = types.Int64Value(int64(result.Priority))
	plan.Enabled = types.BoolValue(result.Enabled)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *discovery_ruleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state discovery_ruleResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	err = r.client.DeleteForemanDiscoveryRule(ctx, id)
	if err != nil && !generated.IsNotFoundError(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete discovery_rule, got error: %s", err))
		return
	}
}

func (r *discovery_ruleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
