// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	attr "github.com/hashicorp/terraform-plugin-framework/attr"
	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	schema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	planmodifier "github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	stringplanmodifier "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	types "github.com/hashicorp/terraform-plugin-framework/types"
	tflog "github.com/hashicorp/terraform-plugin-log/tflog"
	generated "github.com/terraform-coop/terraform-provider-foreman/generated"
	"strconv"
)

var _ resource.Resource = &domainResource{}
var _ resource.ResourceWithImportState = &domainResource{}

func NewForemanDomainResource() resource.Resource {
	return &domainResource{}
}

type domainResource struct {
	client *generated.ForemanClient
}

type domainResourceModel struct {
	ID                         types.String `tfsdk:"id"`
	Name                       types.String `tfsdk:"name"`
	DNSID                      types.Int64  `tfsdk:"dns_id"`
	DomainParametersAttributes types.List   `tfsdk:"domain_parameters_attributes"`
	Fullname                   types.String `tfsdk:"fullname"`
}

func (r *domainResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_domain"
}

func (r *domainResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{Attributes: map[string]schema.Attribute{
		"dns_id": schema.Int64Attribute{
			Description: "DNS proxy ID to use within this domain",
			Optional:    true,
			Required:    false,
		},
		"domain_parameters_attributes": schema.ListAttribute{
			Description: "Array of parameters (name, value)",
			ElementType: types.Int64Type,
			Optional:    true,
			Required:    false,
		},
		"fullname": schema.StringAttribute{
			Description: "Description of the domain",
			Optional:    true,
			Required:    false,
		},
		"id": schema.StringAttribute{
			Computed:      true,
			PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
		},
		"name": schema.StringAttribute{
			Description: "The full DNS domain name",
			Required:    true,
		},
	}}
}

func (r *domainResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}

func (r *domainResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan domainResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanDomainRequest{
		DNSID: plan.DNSID.ValueInt64(),
		DomainParametersAttributes: func() []int64 {
			if plan.DomainParametersAttributes.IsNull() || plan.DomainParametersAttributes.IsUnknown() {
				return nil
			}
			var ids []int64
			for _, v := range plan.DomainParametersAttributes.Elements() {
				if iv, ok := v.(types.Int64); ok {
					ids = append(ids, iv.ValueInt64())
				}
			}
			return ids
		}(),
		Fullname: plan.Fullname.ValueString(),
		Name:     plan.Name.ValueString(),
	}

	result, err := r.client.CreateForemanDomain(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create domain, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.Name = types.StringValue(result.Name)
	plan.DNSID = types.Int64Value(int64(result.DNSID))
	plan.Fullname = types.StringValue(result.Fullname)

	tflog.Trace(ctx, "created domain", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *domainResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state domainResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanDomain(ctx, id)
	if err != nil {
		if generated.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read domain, got error: %s", err))
		return
	}

	state.Name = types.StringValue(result.Name)
	state.DNSID = types.Int64Value(int64(result.DNSID))
	if result.DomainParametersAttributes != nil {
		elems := make([]attr.Value, len(result.DomainParametersAttributes))
		for i, v := range result.DomainParametersAttributes {
			elems[i] = types.Int64Value(int64(v))
		}
		state.DomainParametersAttributes = types.ListValueMust(types.Int64Type, elems)
	} else {
		state.DomainParametersAttributes = types.ListNull(types.Int64Type)
	}
	state.Fullname = types.StringValue(result.Fullname)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *domainResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan domainResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanDomainRequest{
		DNSID: plan.DNSID.ValueInt64(),
		DomainParametersAttributes: func() []int64 {
			if plan.DomainParametersAttributes.IsNull() || plan.DomainParametersAttributes.IsUnknown() {
				return nil
			}
			var ids []int64
			for _, v := range plan.DomainParametersAttributes.Elements() {
				if iv, ok := v.(types.Int64); ok {
					ids = append(ids, iv.ValueInt64())
				}
			}
			return ids
		}(),
		Fullname: plan.Fullname.ValueString(),
		Name:     plan.Name.ValueString(),
	}

	result, err := r.client.UpdateForemanDomain(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update domain, got error: %s", err))
		return
	}

	plan.Name = types.StringValue(result.Name)
	plan.DNSID = types.Int64Value(int64(result.DNSID))
	plan.Fullname = types.StringValue(result.Fullname)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *domainResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state domainResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	err = r.client.DeleteForemanDomain(ctx, id)
	if err != nil && !generated.IsNotFoundError(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete domain, got error: %s", err))
		return
	}
}

func (r *domainResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
