// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-coop/terraform-provider-foreman/generated"
)

var (
	_ resource.Resource                = &hostResource{}
	_ resource.ResourceWithImportState = &hostResource{}
)

func NewForemanHostResource() resource.Resource {
	return &hostResource{}
}

type hostResource struct {
	client *generated.ForemanClient
}

type hostResourceModel struct {
	ID                      types.String `tfsdk:"id"`
	BmcAvailable            types.Bool   `tfsdk:"bmc_available"`
	BuildStatus             types.Int64  `tfsdk:"build_status"`
	BuildStatusLabel        types.String `tfsdk:"build_status_label"`
	Certname                types.String `tfsdk:"certname"`
	Comment                 types.String `tfsdk:"comment"`
	ComputeResourceProvider types.String `tfsdk:"compute_resource_provider"`
	Creator                 types.String `tfsdk:"creator"`
	CreatorID               types.Int64  `tfsdk:"creator_id"`
	Disk                    types.String `tfsdk:"disk"`
	DisplayName             types.String `tfsdk:"display_name"`
	GlobalStatus            types.Int64  `tfsdk:"global_status"`
	GlobalStatusFulltext    types.List   `tfsdk:"global_status_fulltext"`
	GlobalStatusLabel       types.String `tfsdk:"global_status_label"`
	HostgroupTitle          types.String `tfsdk:"hostgroup_title"`
	InitiatedAt             types.String `tfsdk:"initiated_at"`
	InstalledAt             types.String `tfsdk:"installed_at"`
	IP                      types.String `tfsdk:"ip"`
	IP6                     types.String `tfsdk:"ip6"`
	LastCompile             types.String `tfsdk:"last_compile"`
	LastReport              types.String `tfsdk:"last_report"`
	MAC                     types.String `tfsdk:"mac"`
	OperatingsystemIcon     types.String `tfsdk:"operatingsystem_icon"`
	OwnerName               types.String `tfsdk:"owner_name"`
	Permissions             types.Map    `tfsdk:"permissions"`
	PXELoader               types.String `tfsdk:"pxe_loader"`
	RebuildRequiresPoweroff types.Bool   `tfsdk:"rebuild_requires_poweroff"`
	SpIP                    types.String `tfsdk:"sp_ip"`
	SpMAC                   types.String `tfsdk:"sp_mac"`
	SpName                  types.String `tfsdk:"sp_name"`
	SpSubnetID              types.String `tfsdk:"sp_subnet_id"`
	UseImage                types.String `tfsdk:"use_image"`
}

func (r *hostResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_host"
}

func (r *hostResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"bmc_available": schema.BoolAttribute{
				Computed: true,
			},
			"build_status": schema.Int64Attribute{
				Computed: true,
			},
			"build_status_label": schema.StringAttribute{
				Computed: true,
			},
			"certname": schema.StringAttribute{
				Computed: true,
			},
			"comment": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"compute_resource_provider": schema.StringAttribute{
				Computed: true,
			},
			"creator": schema.StringAttribute{
				Computed: true,
			},
			"creator_id": schema.Int64Attribute{
				Computed: true,
			},
			"disk": schema.StringAttribute{
				Computed: true,
			},
			"display_name": schema.StringAttribute{
				Computed: true,
			},
			"global_status": schema.Int64Attribute{
				Computed: true,
			},
			"global_status_fulltext": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
			},
			"global_status_label": schema.StringAttribute{
				Computed: true,
			},
			"hostgroup_title": schema.StringAttribute{
				Computed: true,
			},
			"initiated_at": schema.StringAttribute{
				Computed: true,
			},
			"installed_at": schema.StringAttribute{
				Computed: true,
			},
			"ip": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"ip6": schema.StringAttribute{
				Computed: true,
			},
			"last_compile": schema.StringAttribute{
				Computed: true,
			},
			"last_report": schema.StringAttribute{
				Computed: true,
			},
			"mac": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"operatingsystem_icon": schema.StringAttribute{
				Computed: true,
			},
			"owner_name": schema.StringAttribute{
				Computed: true,
			},
			"permissions": schema.MapAttribute{
				Computed: true,
			},
			"pxe_loader": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"rebuild_requires_poweroff": schema.BoolAttribute{
				Computed: true,
			},
			"sp_ip": schema.StringAttribute{
				Computed: true,
			},
			"sp_mac": schema.StringAttribute{
				Computed: true,
			},
			"sp_name": schema.StringAttribute{
				Computed: true,
			},
			"sp_subnet_id": schema.StringAttribute{
				Computed: true,
			},
			"use_image": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

func (r *hostResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}
func (r *hostResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan hostResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanHostRequest{
		Comment:   plan.Comment.ValueString(),
		IP:        plan.IP.ValueString(),
		MAC:       plan.MAC.ValueString(),
		PXELoader: plan.PXELoader.ValueString(),
	}

	result, err := r.client.CreateForemanHost(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create host, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.BmcAvailable = types.BoolValue(result.BmcAvailable)
	plan.BuildStatus = types.Int64Value(int64(result.BuildStatus))
	plan.BuildStatusLabel = types.StringValue(result.BuildStatusLabel)
	plan.Certname = types.StringValue(result.Certname)
	plan.Comment = types.StringValue(result.Comment)
	plan.ComputeResourceProvider = types.StringValue(result.ComputeResourceProvider)
	plan.Creator = types.StringValue(result.Creator)
	plan.CreatorID = types.Int64Value(int64(result.CreatorID))
	plan.Disk = types.StringValue(result.Disk)
	plan.DisplayName = types.StringValue(result.DisplayName)
	plan.GlobalStatus = types.Int64Value(int64(result.GlobalStatus))
	plan.GlobalStatusLabel = types.StringValue(result.GlobalStatusLabel)
	plan.HostgroupTitle = types.StringValue(result.HostgroupTitle)
	plan.InitiatedAt = types.StringValue(result.InitiatedAt)
	plan.InstalledAt = types.StringValue(result.InstalledAt)
	plan.IP = types.StringValue(result.IP)
	plan.IP6 = types.StringValue(result.IP6)
	plan.LastCompile = types.StringValue(result.LastCompile)
	plan.LastReport = types.StringValue(result.LastReport)
	plan.MAC = types.StringValue(result.MAC)
	plan.OperatingsystemIcon = types.StringValue(result.OperatingsystemIcon)
	plan.OwnerName = types.StringValue(result.OwnerName)
	plan.PXELoader = types.StringValue(result.PXELoader)
	plan.RebuildRequiresPoweroff = types.BoolValue(result.RebuildRequiresPoweroff)
	plan.SpIP = types.StringValue(result.SpIP)
	plan.SpMAC = types.StringValue(result.SpMAC)
	plan.SpName = types.StringValue(result.SpName)
	plan.SpSubnetID = types.StringValue(result.SpSubnetID)
	plan.UseImage = types.StringValue(result.UseImage)

	tflog.Trace(ctx, "created host", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *hostResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state hostResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanHost(ctx, id)
	if err != nil {
		if generated.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read host, got error: %s", err))
		return
	}
	state.BmcAvailable = types.BoolValue(result.BmcAvailable)
	state.BuildStatus = types.Int64Value(int64(result.BuildStatus))
	state.BuildStatusLabel = types.StringValue(result.BuildStatusLabel)
	state.Certname = types.StringValue(result.Certname)
	state.Comment = types.StringValue(result.Comment)
	state.ComputeResourceProvider = types.StringValue(result.ComputeResourceProvider)
	state.Creator = types.StringValue(result.Creator)
	state.CreatorID = types.Int64Value(int64(result.CreatorID))
	state.Disk = types.StringValue(result.Disk)
	state.DisplayName = types.StringValue(result.DisplayName)
	state.GlobalStatus = types.Int64Value(int64(result.GlobalStatus))
	state.GlobalStatusLabel = types.StringValue(result.GlobalStatusLabel)
	state.HostgroupTitle = types.StringValue(result.HostgroupTitle)
	state.InitiatedAt = types.StringValue(result.InitiatedAt)
	state.InstalledAt = types.StringValue(result.InstalledAt)
	state.IP = types.StringValue(result.IP)
	state.IP6 = types.StringValue(result.IP6)
	state.LastCompile = types.StringValue(result.LastCompile)
	state.LastReport = types.StringValue(result.LastReport)
	state.MAC = types.StringValue(result.MAC)
	state.OperatingsystemIcon = types.StringValue(result.OperatingsystemIcon)
	state.OwnerName = types.StringValue(result.OwnerName)
	state.PXELoader = types.StringValue(result.PXELoader)
	state.RebuildRequiresPoweroff = types.BoolValue(result.RebuildRequiresPoweroff)
	state.SpIP = types.StringValue(result.SpIP)
	state.SpMAC = types.StringValue(result.SpMAC)
	state.SpName = types.StringValue(result.SpName)
	state.SpSubnetID = types.StringValue(result.SpSubnetID)
	state.UseImage = types.StringValue(result.UseImage)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *hostResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan hostResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanHostRequest{
		Comment:   plan.Comment.ValueString(),
		IP:        plan.IP.ValueString(),
		MAC:       plan.MAC.ValueString(),
		PXELoader: plan.PXELoader.ValueString(),
	}

	result, err := r.client.UpdateForemanHost(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update host, got error: %s", err))
		return
	}
	plan.BmcAvailable = types.BoolValue(result.BmcAvailable)
	plan.BuildStatus = types.Int64Value(int64(result.BuildStatus))
	plan.BuildStatusLabel = types.StringValue(result.BuildStatusLabel)
	plan.Certname = types.StringValue(result.Certname)
	plan.Comment = types.StringValue(result.Comment)
	plan.ComputeResourceProvider = types.StringValue(result.ComputeResourceProvider)
	plan.Creator = types.StringValue(result.Creator)
	plan.CreatorID = types.Int64Value(int64(result.CreatorID))
	plan.Disk = types.StringValue(result.Disk)
	plan.DisplayName = types.StringValue(result.DisplayName)
	plan.GlobalStatus = types.Int64Value(int64(result.GlobalStatus))
	plan.GlobalStatusLabel = types.StringValue(result.GlobalStatusLabel)
	plan.HostgroupTitle = types.StringValue(result.HostgroupTitle)
	plan.InitiatedAt = types.StringValue(result.InitiatedAt)
	plan.InstalledAt = types.StringValue(result.InstalledAt)
	plan.IP = types.StringValue(result.IP)
	plan.IP6 = types.StringValue(result.IP6)
	plan.LastCompile = types.StringValue(result.LastCompile)
	plan.LastReport = types.StringValue(result.LastReport)
	plan.MAC = types.StringValue(result.MAC)
	plan.OperatingsystemIcon = types.StringValue(result.OperatingsystemIcon)
	plan.OwnerName = types.StringValue(result.OwnerName)
	plan.PXELoader = types.StringValue(result.PXELoader)
	plan.RebuildRequiresPoweroff = types.BoolValue(result.RebuildRequiresPoweroff)
	plan.SpIP = types.StringValue(result.SpIP)
	plan.SpMAC = types.StringValue(result.SpMAC)
	plan.SpName = types.StringValue(result.SpName)
	plan.SpSubnetID = types.StringValue(result.SpSubnetID)
	plan.UseImage = types.StringValue(result.UseImage)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *hostResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state hostResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	err = r.client.DeleteForemanHost(ctx, id)
	if err != nil && !generated.IsNotFoundError(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete host, got error: %s", err))
		return
	}
}

func (r *hostResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
