// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/terraform-coop/terraform-provider-foreman/generated"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &defaulttemplateResource{}
	_ resource.ResourceWithImportState = &defaulttemplateResource{}
)

func NewForemanDefaultTemplateResource() resource.Resource {
	return &defaulttemplateResource{}
}

type defaulttemplateResource struct {
	client *generated.ForemanClient
}

type defaulttemplateResourceModel struct {
	ID                     types.String `tfsdk:"id"`
	ProvisioningTemplateID types.Int64  `tfsdk:"provisioning_template_id"`
	TemplateKindID         types.Int64  `tfsdk:"template_kind_id"`
}

func (r *defaulttemplateResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_defaulttemplate"
}

func (r *defaulttemplateResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"provisioning_template_id": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Description: "ID of provisioning template",
			},
			"template_kind_id": schema.Int64Attribute{
				Required: false,
				Optional: true,
			},
		},
	}
}

func (r *defaulttemplateResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}
func (r *defaulttemplateResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan defaulttemplateResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanDefaultTemplateRequest{
		ProvisioningTemplateID: plan.ProvisioningTemplateID.ValueInt64(),
		TemplateKindID:         plan.TemplateKindID.ValueInt64(),
	}

	result, err := r.client.CreateForemanDefaultTemplate(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create defaulttemplate, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.ProvisioningTemplateID = types.Int64Value(int64(result.ProvisioningTemplateID))
	plan.TemplateKindID = types.Int64Value(int64(result.TemplateKindID))

	tflog.Trace(ctx, "created defaulttemplate", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *defaulttemplateResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state defaulttemplateResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanDefaultTemplate(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read defaulttemplate, got error: %s", err))
		return
	}
	state.ProvisioningTemplateID = types.Int64Value(result.ProvisioningTemplateID)
	state.TemplateKindID = types.Int64Value(result.TemplateKindID)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *defaulttemplateResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan defaulttemplateResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanDefaultTemplateRequest{
		ProvisioningTemplateID: plan.ProvisioningTemplateID.ValueInt64(),
		TemplateKindID:         plan.TemplateKindID.ValueInt64(),
	}

	result, err := r.client.UpdateForemanDefaultTemplate(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update defaulttemplate, got error: %s", err))
		return
	}
	plan.ProvisioningTemplateID = types.Int64Value(int64(result.ProvisioningTemplateID))
	plan.TemplateKindID = types.Int64Value(int64(result.TemplateKindID))

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *defaulttemplateResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state defaulttemplateResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	err = r.client.DeleteForemanDefaultTemplate(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete defaulttemplate, got error: %s", err))
		return
	}
}

func (r *defaulttemplateResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
