// Code generated by tools/gen/client/main.go. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-coop/terraform-provider-foreman/generated"
)

var (
	_ resource.Resource                = &modelResource{}
	_ resource.ResourceWithImportState = &modelResource{}
)

func NewForemanModelResource() resource.Resource {
	return &modelResource{}
}

type modelResource struct {
	client *generated.ForemanClient
}

type modelResourceModel struct {
	ID            types.String `tfsdk:"id"`
	HardwareModel types.String `tfsdk:"hardware_model"`
	HostsCount    types.Int64  `tfsdk:"hosts_count"`
	Info          types.String `tfsdk:"info"`
	VendorClass   types.String `tfsdk:"vendor_class"`
}

func (r *modelResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_model"
}

func (r *modelResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"hardware_model": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"hosts_count": schema.Int64Attribute{
				Computed: true,
			},
			"info": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
			"vendor_class": schema.StringAttribute{
				Required: false,
				Optional: true,
			},
		},
	}
}

func (r *modelResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*generated.ForemanClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Provider Data", "Expected *generated.ForemanClient")
		return
	}
	r.client = client
}
func (r *modelResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan modelResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := &generated.ForemanModelRequest{
		HardwareModel: plan.HardwareModel.ValueString(),
		Info:          plan.Info.ValueString(),
		VendorClass:   plan.VendorClass.ValueString(),
	}

	result, err := r.client.CreateForemanModel(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create model, got error: %s", err))
		return
	}

	plan.ID = types.StringValue(strconv.Itoa(int(result.ID)))
	plan.HardwareModel = types.StringValue(result.HardwareModel)
	plan.HostsCount = types.Int64Value(int64(result.HostsCount))
	plan.Info = types.StringValue(result.Info)
	plan.VendorClass = types.StringValue(result.VendorClass)

	tflog.Trace(ctx, "created model", map[string]interface{}{"id": plan.ID.ValueString()})
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *modelResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state modelResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	result, err := r.client.ReadForemanModel(ctx, id)
	if err != nil {
		if generated.IsNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read model, got error: %s", err))
		return
	}
	state.HardwareModel = types.StringValue(result.HardwareModel)
	state.HostsCount = types.Int64Value(int64(result.HostsCount))
	state.Info = types.StringValue(result.Info)
	state.VendorClass = types.StringValue(result.VendorClass)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *modelResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan modelResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	body := &generated.ForemanModelRequest{
		HardwareModel: plan.HardwareModel.ValueString(),
		Info:          plan.Info.ValueString(),
		VendorClass:   plan.VendorClass.ValueString(),
	}

	result, err := r.client.UpdateForemanModel(ctx, id, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update model, got error: %s", err))
		return
	}
	plan.HardwareModel = types.StringValue(result.HardwareModel)
	plan.HostsCount = types.Int64Value(int64(result.HostsCount))
	plan.Info = types.StringValue(result.Info)
	plan.VendorClass = types.StringValue(result.VendorClass)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *modelResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state modelResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	id, err := strconv.Atoi(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", fmt.Sprintf("Unable to parse ID: %s", err))
		return
	}

	err = r.client.DeleteForemanModel(ctx, id)
	if err != nil && !generated.IsNotFoundError(err) {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete model, got error: %s", err))
		return
	}
}

func (r *modelResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
